### ISSUE TITLE
🧀🧀🧀🧀🧀🧀🧀 CHEEEEEEEEEEEEEEEESE 🧀🧀🧀🧀🧀🧀🧀

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1000]
tradition: let's make every thousandth ticket a party

![party ticket](https://media.giphy.com/media/oGczu7JhLEcz6/giphy.gif)

![ohhh yeah](https://media.giphy.com/media/WMPQ6NTg9X8Zy/giphy.gif)

![eeeeee](https://media.giphy.com/media/kcog6ebOvhWBW/giphy.gif)

**Comment by TejasQ** [comment]
i think @adeelibr can fix this one

**Comment by adeelibr** [comment]
Oh wow, I am complete game for it @TejasQ Any interesting issue/feature to work on? 💭

**Comment by TejasQ** [comment]
yes more cheese gifs please

**Comment by adeelibr** [comment]
![ImaginarySatisfiedBlowfish-size_restricted](https://user-images.githubusercontent.com/16651811/57788540-8df41100-7737-11e9-9235-ca5364f6cc05.gif)

🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀 🧀

**Comment by adeelibr** [comment]
![4D6x](https://user-images.githubusercontent.com/16651811/57788855-1d99bf80-7738-11e9-809b-ab7959409cfc.gif)

**Comment by TejasQ** [comment]
@gantman please let us know your opinion

**Comment by GantMan** [comment]
Scientific model of my thoughts
![cheese](https://user-images.githubusercontent.com/997157/57800902-1f538b00-7718-11e9-9d0f-9208525287c5.gif)

**Comment by TejasQ** [comment]
I bestow the almight crown on @GantMan 

![image](https://user-images.githubusercontent.com/9947422/57836044-2cc45000-77c0-11e9-910e-9349d5b39dab.png)

**Comment by fabien0102** [comment]
![https://media.giphy.com/media/8u7xTLoDVmwNy/giphy.gif](https://media.giphy.com/media/8u7xTLoDVmwNy/giphy.gif)
