### ISSUE TITLE
Select's context menu does not display labels if only values provided in options

### ISSUE THREAD

**Issue by mpotomin** [contiamo/operational-ui#1032]
Select component does not use values if no labels are provided in options list. Without labels empty list of options is displayed

<img width="285" alt="Screenshot 2019-06-14 at 09 34 33" src="https://user-images.githubusercontent.com/639406/59491819-e548e680-8e87-11e9-8325-d1139fc3ecfc.png">
<img width="219" alt="Screenshot 2019-06-14 at 09 34 47" src="https://user-images.githubusercontent.com/639406/59491820-e548e680-8e87-11e9-8da9-a6034d337232.png">

**Comment by TejasQ** [comment]
wow not a single word

**Comment by mpotomin** [comment]
Fixed with https://github.com/contiamo/operational-ui/pull/1033
