### ISSUE TITLE
Select/Context menu should close when  options is selected

### ISSUE THREAD

**Issue by mpotomin** [contiamo/operational-ui#1056]
[Select](http://operational-ui.netlify.com/#/Components/Select) with a single option should close when the selection is made. 

![Select bug](https://user-images.githubusercontent.com/639406/59831193-9399d380-9341-11e9-9287-45bb72212b8d.gif)

**Comment by TejasQ** [comment]
Is this on @next?

**Comment by mpotomin** [comment]
Causing issue https://github.com/contiamo/operational-ui/pull/1047

**Comment by atsutton** [comment]
Can I take a crack at this? I think I've solved the problem.

**Comment by mpotomin** [comment]
Thx, @atsutton, looks like we've almost got it here  https://github.com/contiamo/operational-ui/pull/1060
