### ISSUE TITLE
AvatarGroup negative margin breaks design

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1076]
Here's a [demo](http://operational-ui.netlify.com/#!/CardColumns) of the problem.

![image](https://user-images.githubusercontent.com/9947422/59972558-5fdfc900-954e-11e9-8d95-cff7b195a893.png)

## The Problem

In `AvatarGroup`, each constituent `Avatar` has `margin-left: -12px`, which breaks their composition into any box model.

## The Solution

Only apply the negative margin to every `Avatar` _after_ the first one.

**Comment by mehtavishwa30** [comment]
Hey!
Checked out the demo. Let's get started on it.

**Comment by TejasQ** [comment]
Great! Are you able to get the project up and running locally?

**Comment by mehtavishwa30** [comment]
Installing packages and setting it up. Anything specific I need to go through in the docs?

**Comment by TejasQ** [comment]
Nothing specific. Everything should be in the README. Looking forward to your PR.

**Comment by winniebosy** [comment]
So how do i go on..I have never made a contribution before.If this goes successful, it will be mu first contribution on github.

**Comment by bradd123** [comment]
@TejasQ After running `yarn` and `yarn start`, I got stuck here. I think this is related to `react-styleguidist`. I have updated the node before running this.
<img width="954" alt="1__node" src="https://user-images.githubusercontent.com/8004676/59977139-417bdb00-95eb-11e9-862b-a128ecf024c1.png">

**Comment by TejasQ** [comment]
@winniebosy @bradd123 hey y'all, thanks for getting involved but these issues are on a first-come-first-serve basis. I believe @mehtavishwa30 already started on it so it would only be fair to her that we let her finish it.

@winniebosy that means there aren't really any other `good first issue`s left for you to choose from. We might ping you later if something comes up. I hope that's okay! 😄 

@bradd123, that's great feedback! It seems there are 2 TS errors. 🤔 I'll investigate this in https://github.com/contiamo/operational-ui/issues/1077 and see what's broken. Thanks for pointing that out!

**Comment by DillionM** [comment]
Permit me to say I don't understand what's going on here.... I'm a GitHub newbie ☹️

**Comment by TejasQ** [comment]
@DillionM, you have all the permission to not understand and that is totally fine! 

To explain a bit,

- this is an **issue**. It's a place where we (the community) list stuff that we need to work on in the project. Think of it as a "to do list".

- when someone (in this case @mehtavishwa30) chooses to work on it, they fix the issue and open a **pull request**. They kind of look [like this](https://github.com/contiamo/operational-ui/pull/1072) and allow us to see what's being added/removed from the project and review it to make sure we're all on the same page.

- if we approve it, then @mehtavishwa30's work becomes part of this project and the issue gets resolved (we check the item of the to do list) and continue to create better software together.

Does that clarify things a bit? Or was your question more about this specific issue?

**Comment by victorgarciaesgi** [comment]
It's just css?

Why not put 

.avatar:not(:first-child) {
     margin-left: -12px;
}

**Comment by TejasQ** [comment]
You could! We’d have to use a theme value instead of just -12, but that can work. 😃

**Comment by mehtavishwa30** [comment]
> Nothing specific. Everything should be in the README. Looking forward to your PR.

The script is returning a few problems in the tsconfig file and AvatarGroup. Although the code looks just fine.

**Comment by TejasQ** [comment]
> The script is returning a few problems in the tsconfig file and AvatarGroup.

What script?

What problems?

Logs/output would be helpful to help me help you in this case. 

> Also, how about just adding a positive padding to the div rather than changing the marginLeft for first child?

I think it’s fundamentally a design question. With design systems, it’s often a bad idea to have elements manipulate the space around them. This is kind of like doing side effects in functions. They’re not wrong necessarily, but often can lead to unpredictable states. 

To help this, the “pure functions” metaphor for design systems IMO is that elements don’t change the space around them but leave that concern up to the parent. This is what #1075 does for example. 

That’s exactly the problem here: it’s dealing with the space around it. 

If you add a padding, it deals more with the space _inside_ it, which I think is a little better. Try it! Let’s see how it goes!

**Comment by mehtavishwa30** [comment]
> What problems?
Attached screenshots of the logs

> Logs/output would be helpful to help me help you in this case.


> I think it’s fundamentally a design question. With design systems, it’s often a bad idea to have elements manipulate the space around them. This is kind of like doing side effects in functions. They’re not wrong necessarily, but often can lead to unpredictable states.

Agreed. It's probably not the best way to solve the problem.

> If you add a padding, it deals more with the space _inside_ it, which I think is a little better. Try it! Let’s see how it goes!
Working on it! Thanks.

**Comment by TejasQ** [comment]
Those errors look a little odd. Do you have TypeScript installed? Maybe try `yarn add typescript@next -D` again?

**Comment by mehtavishwa30** [comment]
> Those errors look a little odd. Do you have TypeScript installed? Maybe try `yarn add typescript@next -D` again?

I do have it priorly installed. However trying that does not solve the problem.

**Comment by Ali-Aftab** [comment]
Hi @TejasQ ,
I was curious if the pull request is still open for grabs

**Comment by TejasQ** [comment]
Hey @Ali-Aftab! Welcome to the project! Unfortunately, this issue was taken on by @mehtavishwa30 and already has an open pull request on which we’re collaborating: https://github.com/contiamo/operational-ui/issues/1081

Feel free to grab any other issue though!

**Comment by bradd123** [comment]
@mehtavishwa30 Have you forked the repo to your account and cloned that repo? I think cloning directly will have problems running locally sometimes.

**Comment by TejasQ** [comment]
@bradd123 say more – why?

**Comment by bradd123** [comment]
This is just my observation. I mistakenly cloned direct URL and tried to run locally, I had some TS errors. https://github.com/contiamo/operational-ui/issues/1077. It worked fine after forking the repo and run locally.

**Comment by TejasQ** [comment]
That is so interesting. I'll have to look into that and see why.

**Comment by TejasQ** [comment]
Oh also, we merged the PR that fixes this issue so I'mma close this now. Thanks so much for your great work, @mehtavishwa30!
