### ISSUE TITLE
Tree is completely inaccessible

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1085]
Tabbing around [here](https://deploy-preview-1083--operational-ui.netlify.com/#/Components/Tree) doesn't allow us to do anything with the tree (expand or collapse nodes) via keyboard.

This is _bad_.

Let's fix it.

**Comment by wptechprodigy** [comment]
Hi @TejasQ 

I want to take this issue.

I'll read through to get an understanding and discuss it with you.

**Comment by TejasQ** [comment]
You got it!

**Comment by TejasQ** [comment]
To get started I'd recommend reading [this document](https://www.w3.org/TR/wai-aria-practices/examples/treeview/treeview-2/treeview-2a.html) and understanding the expected behavior of an accessible tree view. 🚀

**Comment by wptechprodigy** [comment]
Okay

**Comment by wptechprodigy** [comment]
Hi Tejas.

Thanks for providing the opportunity to gain experience with you.

I went through w3.org ARIA in HTML document yesterday and understood the implementation of the Tree concept for both files and navigation. 

Here are my issues: 
1. I am not familiar with TS yet.
2. I understood that tabbing should work on the list, as well keyboard keys and confused where to look into.
3. I was looking into the Tree subdirectory in the src folder and not sure about TS.
4. I have laptop problem, I work on my Android mobile tablet where I use Termux app for terminal and web-code for editor, so when I tried running yarn install (to install dependencies), I ran into errors unzipping cypress.

What do you think I should do?

**Comment by TejasQ** [comment]
I think we can work with all those points, though point 4 might be a little hard. It might be cool to have a PR created from an Android tablet though. What Cypress errors did you have?

**Comment by wptechprodigy** [comment]
Cannot unzip cypress.

I have looked at the Cypress github page for probable solution but couldn't find something suitable

**Comment by TejasQ** [comment]
It just says `Cannot unzip cypress`? Nothing else?

**Comment by wptechprodigy** [comment]
I couldn't recover the error. I'll try to see if it can be reproduced.

**Comment by wptechprodigy** [comment]
I did a fresh clone of the repo and ran yarn again

Here's the screenshot of the error I got now:

![Error Screenshot](https://res.cloudinary.com/waheedafolabi/image/upload/v1561541920/My%20Ps/Screenshot_2019-06-26-10-34-04.png)

**Comment by wptechprodigy** [comment]
It seems the android platform is not supported for Cypress.

**Comment by TejasQ** [comment]
Yeah, that's a bummer. @brian-mann, is there a plan to support the android platform on Cypress in the near future?

**Comment by wptechprodigy** [comment]
I want to see possibility of borrowing a laptop from a friend and trying it out.

**Comment by wptechprodigy** [comment]
I have gotten a laptop from a friend. I'm setting it up already.

**Comment by TejasQ** [comment]
Awesome! Feel free to get in touch with any questions you may have!

**Comment by wptechprodigy** [comment]
Hey @TejasQ . Everything went well...I ran ```yarn start``` and it did some compilation.

I tried accessing the app on http://192.168.43.77:6060/ as provided on the terminal

![styleguidist](https://user-images.githubusercontent.com/22558674/60345794-aea7bb80-99b1-11e9-875f-f243d57d5b5e.png)

But it keeps running without a visual output.

**Comment by TejasQ** [comment]
Try running `yarn styleguidist server` and see what happens. This is a known bug I'm looking at. https://github.com/contiamo/operational-ui/issues/1107

If `yarn styleguidist server` reports an error, paste it here and we can debug together. If it starts successfully, great! You have a dev server!

**Comment by wptechprodigy** [comment]
Okay! Will try that out and let you know.

**Comment by wptechprodigy** [comment]
Nothing happened.

![styleguidistserver](https://user-images.githubusercontent.com/22558674/60348740-18c35f00-99b8-11e9-8f25-335fb3f5942e.png)
```yarn styleguidist server``` seems to run fine but ```localhost:6060/``` never stops trying to load up something.

I then looked up the script section of the ```package.json``` file and I couldn't find a script command for ```styleguidist server```

Here's a screenshot of the ```package.json``` on my local machine:
![packageJSON](https://user-images.githubusercontent.com/22558674/60349053-c0d92800-99b8-11e9-95b1-5184fb634370.png)

**Comment by wptechprodigy** [comment]
Here's the script section of the ```package.json``` here on the repo:

![githubJSON](https://user-images.githubusercontent.com/22558674/60349917-60e38100-99ba-11e9-88b8-42e8ce20a1e5.png)

**Comment by TejasQ** [comment]
It's not an issue that the script is missing. Nothing really appears to be wrong with your setup: styleguidist just takes a _really long_ time to start – sometimes up to 5 minutes! The team is already aware of it (see https://github.com/styleguidist/react-styleguidist/issues/212).

Would you mind running `yarn styleguidist server` and waiting 5 minutes for it to start?

**Comment by wptechprodigy** [comment]
No, I wouldn't mind.

I'll run it again, wait for 5 minutes+ and let you know.

**Comment by TejasQ** [comment]
Thanks!

**Comment by wptechprodigy** [comment]
Working...

![guidistworking](https://user-images.githubusercontent.com/22558674/60352535-ec134580-99bf-11e9-9bc3-291ead8ffe46.png)

and running live on ```http://localhost:6060/``` :

![operationalUI](https://user-images.githubusercontent.com/22558674/60352647-2b419680-99c0-11e9-8df1-ef8730313d8d.png)

**Comment by TejasQ** [comment]
Nice! You're ready to work! 🚀

**Comment by wptechprodigy** [comment]
Sure...expect my PR on cellWidth first.

**Comment by TejasQ** [comment]
Hey @wptechprodigy, how are you doing on this issue? Do you need help or support with anything?

**Comment by stereobooster** [comment]
It is resolved by https://github.com/contiamo/operational-ui/pull/1301
