### ISSUE TITLE
Fix SectionHeader height

### ISSUE THREAD

**Issue by stereobooster** [contiamo/operational-ui#1087]
There is [SectionHeader](https://github.com/contiamo/operational-ui/blob/master/src/Internals/SectionHeader.tsx) which uses

```
height: theme.space.element * 2,
```

This is wrong because we not suppose to use "space" (something around the content) for content size. 

Task is to change it to use `36px` from new design (do we need constant for it or we already have one?), as well find other occurrences of `theme.space.element * 2` and fix them.

PS SectionHeader is reused for Card headers, Tabs and Accordion

**Comment by TejasQ** [comment]
> do we need constant for it or we already have one?

I don't expect this height to be reused or configurable by a theme for this _opinionated_ UI component library so let's hardcode the number in there.

**Comment by march213** [comment]
Hi 👋🏻 

I’d like to take this issue.

**Comment by TejasQ** [comment]
Hey @march213! Welcome to the project! This issue is now yours! 🎉

**Comment by march213** [comment]
@TejasQ Thank you 🚀
