### ISSUE TITLE
RFC: remove borders

### ISSUE THREAD

**Issue by stereobooster** [contiamo/operational-ui#1088]
Some of our components come with outer border, for example

<img width="1051" alt="Screenshot 2019-06-25 at 10 22 48" src="https://user-images.githubusercontent.com/179534/60082099-68ddbf80-9733-11e9-8175-3f00e6597e54.png">
<img width="307" alt="Screenshot 2019-06-25 at 10 23 07" src="https://user-images.githubusercontent.com/179534/60082100-68ddbf80-9733-11e9-9baf-c1f6ea8a33e1.png">
<img width="330" alt="Screenshot 2019-06-25 at 10 23 22" src="https://user-images.githubusercontent.com/179534/60082101-69765600-9733-11e9-8680-0180a998a8e3.png">

When we put those components side-by-side we get 2px border instead of desired 1px border. Maybe it is good idea not to use outer borders for components which can be place side-by-side?

Except outer borders we have inner borders, for example lines between accordion sections, for those we need to agree to use consistent placement of borders (top or bottom), otherwise we will have off by one pixels in some cases.

**Comment by TejasQ** [comment]
> Maybe it is good idea not to use outer borders for components which can be place side-by-side?

This is a great idea, but then where would the border come from? The parent?

**Comment by stereobooster** [comment]
Yes, some kind of grid component which would be responsible for sizes, position and borders

**Comment by TejasQ** [comment]
I like the sound of that.

**Comment by TejasQ** [comment]
Tbh, `border-collapse` on `div`s would be _amazing_ and solve this problem out of the box. cc @fantasai
