### ISSUE TITLE
TopBarSelect types are broken

### ISSUE THREAD

**Issue by stereobooster** [contiamo/operational-ui#1099]
Consider following code example

```ts
import { BarChartIcon, TableIcon, TopbarSelect } from "@operational/components"

const displayItems = [{ label: "Table", icon: TableIcon }, { label: "Bar Chart", icon: BarChartIcon }]

const [activeDisplay, setActiveDisplay] = React.useState<any>("Table")

;<TopbarSelect
  label="Display:"
  selected={activeDisplay}
  items={displayItems}
  onChange={setActiveDisplay}
/>
```

It doesn't work without `any` in `React.useState`

**Comment by march213** [comment]
Hi 👋🏻 
Can I take this one too ?

**Comment by ImogenF** [comment]
@march213 Go for it!

**Comment by march213** [comment]
@ImogenF Thank you !

**Comment by march213** [comment]
@stereobooster Would it be right to change `onChange` type to this

```
onChange?: (
    newLabel:
      | string
      | React.ReactElement<any>
      | React.Dispatch<React.SetStateAction<string | React.ReactElement<any>>>
  ) => void
```

It works, because in this scenario you are passing `setActiveDisplay` to `onChange`. But `setActiveScenario` has type `React.Dispatch<React.SetStateAction<string>>` which is incompatible with current `onChange?: (newLabel: string | React.ReactElement<any>) => void`

I'm not a TS expert yet 🤓, so maybe I'm wrong.

**Comment by stereobooster** [comment]
@march213 consider following code (standard React)

```js
function App() {
  const [state, setState] = React.useState('mango');
  const onChange = React.useCallback((event) => setState(event.target.value), [])

  return (
    <select value={state} onChange={onChange}>
      <option value="grapefruit">Grapefruit</option>
      <option value="lime">Lime</option>
      <option value="coconut">Coconut</option>
      <option value="mango">Mango</option>
    </select>
  );
}
```

React standard components have to deal with event, because they are building blocks. But in our case we can simplify API and onChange can be called with value directly instead of event. (Does it make sense so far?)

So we should be able to write something like this

```
const displayItems = [{ label: "Table", icon: TableIcon }, { label: "Bar Chart", icon: BarChartIcon }];
const [activeDisplay, setActiveDisplay] = React.useState("Table");

<TopbarSelect
  label="Display:"
  selected={activeDisplay}
  items={displayItems}
  onChange={setActiveDisplay}
/>
```

But our type system says that onChange can be called with ReactNode as well. Does it even make sense to have ReactNode provided to onChange? 🤔 How we gonna use ReactNode in state (I mean generally we can, but we should unless there is a specific reason for it).

So my idea is that `onChange` type signature should be `(label: string | IContextMenuItem) => void`

**Comment by march213** [comment]
Thank you 😊 It makes perfect sense. I will simplify type signature.

> But our type system says that onChange can be called with ReactNode as well. Does it even make sense to have ReactNode provided to onChange? 🤔 How we gonna use ReactNode in state? (I mean generally we can, but we should not unless there is a specific reason for it).

I was confusing about using ReactNode, but I wasn't sure about use cases.

**Comment by march213** [comment]
Found another problem:

```ts
<ContextMenu
      condensed
      items={items}
      width={containerWidth}
      onClick={newItem => {
        if (onChange) {
          onChange(newItem.label)
        }
      }}
    >
      {isActive => (
       ....
      )}
    </ContextMenu>
```

In this example `newItem.label` that passes to onChange has type signature of `label: string | React.ReactElement<any>`. The file is `ContextMenu.Item.tsx` -> IContextMenuItem.

Should I change this label type signature to `label: string` as well ?
@stereobooster

**Comment by march213** [comment]
I run tests, and I get a lot of errors, if change type signature to`label: string` for IContextMenuItem.
This for example.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/8292471/60352112-2f0bf380-9995-11e9-83bd-d660a78ec501.png">

**Comment by TejasQ** [comment]
Please do not change the type signature of `IContextMenuItem`. This is used widely internally and could be a significant breaking change.

Further, sometimes the labels of these items (even in `TopbarSelect`) are not directly equal to the value. Imagine a list where you want to show user-readable labels but have machine-readable values. In this case, you'd want to pass [`newItem.value`](https://github.com/contiamo/operational-ui/blob/a432c8e90277345b31e11ec30fb02599ddaf7e77/src/ContextMenu/ContextMenu.Item.tsx#L30) to `onChange`.

For these reasons, I think passing just a label is a little naïve compared to passing the entire item and letting the user deal with it however they want.

**Comment by stereobooster** [comment]
This sometimes happens https://www.youtube.com/watch?v=_UZFI-8D5uA

**Comment by march213** [comment]
@TejasQ Yeah, this is what happened when I run tests.

**Comment by march213** [comment]
> For consistency across our app, I propose the following interface for TopbarSelect:

> ```onClick: ContextMenuProps["onClick"]```

> This should make things more compatible.

But this won't work with type `string`

```
Argument of type 'string | ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>' is not assignable to parameter of type 'IContextMenuItem<any>'.

  Type 'string' is not assignable to type 'IContextMenuItem<any>'.
```

**Comment by TejasQ** [comment]
I think this is fine. @stereobooster would need to update his code to look like this:

```tsx
const displayItems = [{ label: "Table", icon: TableIcon }, { label: "Bar Chart", icon: BarChartIcon }];
const [activeDisplay, setActiveDisplay] = React.useState("Table");

<TopbarSelect
  label="Display:"
  selected={activeDisplay}
  items={displayItems}
  onChange={item => setActiveDisplay(item.label)}
/>
```

I think this makes sense for the reasons I mentioned above. Namely,

> sometimes the labels of these items (even in TopbarSelect) are not directly equal to the value. Imagine a list where you want to show user-readable labels but have machine-readable values. In this case, you'd want to pass newItem.value to onChange instead of its label.

**Comment by march213** [comment]
Right now problem is here:
```
 return (
    <ContextMenu
      condensed
      items={items}
      width={containerWidth}
      onClick={newItem => {
        if (onChange) {
          onChange(newItem.label)
        }
      }}
    >
      {isActive => (
        <TopbarSelectContainer {...props} isActive={isActive} ref={containerRef}>
          <TopbarSelectLabel>{label}</TopbarSelectLabel>
          <TopbarSelectValue>
            {Icon && <Icon left />}
            <TopbarSelectValueSpan>{selected}</TopbarSelectValueSpan>
            {React.createElement(isActive ? CaretUpIcon : CaretDownIcon, { size: 10, color: "color.text.lightest" })}
          </TopbarSelectValue>
        </TopbarSelectContainer>
      )}
    </ContextMenu>
  )
```

Where we pass `newItem.label` to `onChange`

**Comment by TejasQ** [comment]
Yes you can.
