### ISSUE TITLE
TopBarSelect is off by some pixels

### ISSUE THREAD

**Issue by stereobooster** [contiamo/operational-ui#1100]
As you can see TopBarSelect is not on the same line as buttons. Font size is a bit smaller. Arrow is too big.

Current:
<img width="271" alt="Screenshot 2019-06-27 at 10 37 10" src="https://user-images.githubusercontent.com/179534/60250898-cc98f180-98c7-11e9-902c-04ad99fd77e8.png">

Design:
<img width="267" alt="Screenshot 2019-06-27 at 13 05 08" src="https://user-images.githubusercontent.com/179534/60261490-5357c980-98dc-11e9-861c-41d362a71f50.png">

**Comment by march213** [comment]
I'd like to take this one too, if you don't mind 😊

**Comment by TejasQ** [comment]
Wow, sure!

**Comment by march213** [comment]
I changed only icon size and font size.
I think it looks better now. What do you think?

__Now__:
<img width="368" alt="Screen Shot 2019-06-29 at 11 16 37 PM" src="https://user-images.githubusercontent.com/8292471/60391764-1e0dd000-9ac4-11e9-993e-670015fb6b58.png">

But CaretIcon looks different, should I change it too?


Also, I noticed that in the `Topbar` Component `NoIcon` looks giant too...
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/8292471/60391786-a55b4380-9ac4-11e9-90ae-4ef3359478c8.png">

@stereobooster

**Comment by stereobooster** [comment]
@march213 don't be shy to open PR without asking for it, if it's not final you can mark it as draft. (I always open PRs without asking to any repo `¯\_(ツ)_/¯`)

It looks good enough on my taste
