### ISSUE TITLE
Make minmax(200px, 1fr) the default cellWidth on DataTable

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1104]
We've found this to be a good reasonable default by dogfooding. Let's set the `cellWidth` prop's default value to be `minmax(200px, 1fr)` on `DataTable`.

**Comment by wptechprodigy** [comment]
I want this as well @TejasQ, already figured it out.

**Comment by TejasQ** [comment]
Do it.

**Comment by wptechprodigy** [comment]
How would this change be tested @TejasQ ?

**Comment by wptechprodigy** [comment]
Under what category should this change be placed: **Feature:** or **Fix:**?

I am thinking **Feature**, what do you think?

**Comment by TejasQ** [comment]
Either or. Great work!
