### ISSUE TITLE
Tabs onActive callback called twice for each action

### ISSUE THREAD

**Issue by stereobooster** [contiamo/operational-ui#1113]
If you go to online playground https://operational-ui.netlify.com/#/Components/Tabs and change code like this:

```diff
- <Tabs tabs={tabs} active={active} onActivate={setActive} onClose={onClose} onInsert={onInsert}>
+ <Tabs tabs={tabs} active={active} onActivate={(x) => { console.log(`onActivate ${x}`); setActive(x);} } onClose={onClose} onInsert={onInsert}>
```

And then click any tab you will see it is called twice

![image](https://user-images.githubusercontent.com/179534/60497441-24af6980-9cb5-11e9-90a6-ffa07d439932.png)

**Comment by kazionovm** [comment]
Hi, can I take this?

**Comment by stereobooster** [comment]
Hi. You can 👍 . Ping me if you need more guidance

**Comment by kazionovm** [comment]
@stereobooster take a look at this screenshot
<img width="100%" alt="image" src="https://user-images.githubusercontent.com/38687326/60802362-5cb91f80-a181-11e9-8716-1826b0ea4eda.png">

When we only creating a new item it calls once, but when we focus on item it occurs twice
This can be happened by ```onActivate``` prop or ```setActive``` method

**Comment by stereobooster** [comment]
My guess the issue is here 

```diff
              <TabHeader
                center={!scroll}
                tabIndex={i === active ? 0 : -1}
                first={i === 0}
                aria-selected={i === active}
                aria-controls={`TabPanel-${uid}-${i}`}
                id={`TabHeader-${uid}-${i}`}
                key={i}
                onClick={onClick}
-                onFocus={onClick}
                ref={i === active ? activeTab : undefined}
              >
```

We don't need to track focus at all. We only need to react on keyboard and clicks

**Comment by kazionovm** [comment]
@stereobooster I'll try it now :)

**Comment by kazionovm** [comment]
@stereobooster check my first contribution to open source 😍
