### ISSUE TITLE
Use Chevron icons instead of + and - in Tree

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1114]
Currently, our [`Tree`](https://operational-ui.netlify.com/#!/Tree) has `+` and `-` to toggle nodes that contain children. Let's use `ChevronRightIcon` and `ChevronDownIcon` here instead to convey intent more meaningfully.

**Comment by iamshadmirza** [comment]
I will be trying on this issue.

**Comment by TejasQ** [comment]
You got it! Looking forward to your PR!

**Comment by iamshadmirza** [comment]
It looks like I have to replace Icon imports in TreeItem.tsx. Please guide.

**Comment by TejasQ** [comment]
You're totally right. You'll want to replace the existing icons with `ChevronRightIcon` and `ChevronDownIcon` I believe. 

Please feel free to reach out with any concrete questions you have as you continue.

**Comment by TejasQ** [comment]
Closed in https://github.com/contiamo/operational-ui/pull/1115
