### ISSUE TITLE
Need to fix unfiltered props in styled components

### ISSUE THREAD

**Issue by stereobooster** [contiamo/operational-ui#1117]
# The Problem

<img width="636" src="https://user-images.githubusercontent.com/179534/60587780-96f77b00-9d95-11e9-9d92-ef36d326463a.png" alt="index.js:3671 Warning: Received `false` for a non-boolean attribute `fill`. If you want to write it to the DOM, pass a string instead: fill='false' or fill={value.toString()}. If you used to conditionally omit it with fill={condition && value}, pass fill={condition ? value : undefined} instead.    in div (created by Context.Consumer)    in Styled(div) (created by Tabs)">

# The Solution

Let's use [Emotion's `shouldForwardProp`](https://emotion.sh/docs/styled#customizing-prop-forwarding) to filter out non-standard attributes on DOM nodes across the library.

# How do I know it's fixed?

There should be no errors or warnings in the console on `localhost:6060` on each component page in the styleguide.

**Comment by march213** [comment]
Hi 👋🏻
I'd like to take this one too.

**Comment by TejasQ** [comment]
Sure! Appreciate your great work!

**Comment by march213** [comment]
@stereobooster @TejasQ 

Hi! I found a problem:
- An Icon component accepts right and left prop. But as I can see, icons are created on build stage and all props are spreaded to an `<svg>`:

```ts
export const RemoveIcon = ({ size = 18, color, left, right, ...props }: IconProps) => {
  const iconColor: string = expandColor(constants, color) || "currentColor"
  const style = {
    // theme.space.small
    marginLeft: right ? 8 : 0,
    // theme.space.small
    marginRight: left ? 8 : 0,
    cursor: Boolean(props.onClick) ? "pointer" : "default",
    transition: "fill .075s ease",
  }
  return (
    <svg viewBox="0 0 17 17" fill={iconColor} width={size} height={size} style={style} {...props}>
      ...
    </svg>
  )
}

```

I'm not sure, how to modify `build-icons.ts` script to prevent it... Any suggestions ?

**Comment by stereobooster** [comment]
@march213 what the problem exactly? 

<img width="875" alt="Screenshot 2019-07-05 at 17 20 52" src="https://user-images.githubusercontent.com/179534/60732025-458fed00-9f49-11e9-826c-382b861ee830.png">

`...props` contains everything except `size, color, left, right`

**Comment by march213** [comment]
@stereobooster I thought that the problem is here:

`Button.tsx`
```ts
  {Icon && iconPosition === "start" && <Icon left {...iconProps} />}
  {children}
  {Icon && iconPosition === "end" && <Icon right {...iconProps} />}
  {props.loading && <ButtonSpinner containerColor={color} />}
```

I thought that somehow the `right` prop passes to an svg in the `ProgressPanel` component. But I didn't check compiled html 🤦🏼‍♀️

Now, I see there is a problem with `Remove` icon:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/8292471/60745255-78d17c80-9f47-11e9-9a44-869a0f34fa04.png">

Not sure what is going on.

**Comment by march213** [comment]
Problem fixed.
