### ISSUE TITLE
Improve DataTable cells

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1120]
Currently our [`DataTable`](http://operational-ui.netlify.com/#!/DataTable) has a bit of clunkiness:

![image](https://user-images.githubusercontent.com/9947422/60670448-f24a6b80-9e70-11e9-97bb-6de76a6d0c65.png)

There's enough room to render a full result, but it doesn't – the default [`maxCharactersInCell`](https://github.com/contiamo/operational-ui/blob/bb84d4eee848978eeae2292496b3044733dc7b3a/src/DataTable/DataTable.tsx#L37) prop kicks in and the contents of a cell truncate for no reason. 

I propose we improve this in the following way:

- If a cell goes past the `maxCharactersInCell`, 
  - add a "more options" icon, that when clicked, (like this 
![image](https://user-images.githubusercontent.com/9947422/60678954-67746b80-9e86-11e9-910c-ee0363fad03a.png))
    - opens a little tooltip/hint/modal with the full contents of the cell 
    - it opens wherever there's free space around it
    - the hint closes on click outside

**Comment by march213** [comment]
👋🏻 I'd like to take this one two 🤓

**Comment by TejasQ** [comment]
Wow! You're on fire, @march213! Let's do it!

**Comment by march213** [comment]
👋🏻 I'm going to work on this on Thursday.

**Comment by TejasQ** [comment]
AWESOME! Thanks so much!

**Comment by TejasQ** [comment]
@march213 how's progress on this? Can I help with anything?

**Comment by march213** [comment]
@TejasQ  Oh, I'm sorry, didn't notice this comment. I'll work on right now.

**Comment by march213** [comment]
Experienced some problems with starting...

![image](https://user-images.githubusercontent.com/8292471/61242624-3280d800-a714-11e9-9af9-f245b8bc59f9.png)

![image](https://user-images.githubusercontent.com/8292471/61242632-3ca2d680-a714-11e9-8fab-e240faeb2b28.png)

**Comment by TejasQ** [comment]
This is a little more pressing of a task because it directly impacts the usability of this component.

For example:

![image](https://user-images.githubusercontent.com/9947422/61275243-d66a9200-a7ad-11e9-9cf4-67bde9d016a9.png)

Do you mind if I take it over? You can always watch the issue to see how we fix it.

**Comment by march213** [comment]
@TejasQ Sure! Sorry about that.
I'm not sure what happened and why it's stopped working. I tried to wait ~7 min but nothing happened.

Anyway, I don't want to block you and looking forward to contribute more.

**Comment by march213** [comment]
@TejasQ Hi 👋🏻. You can take it over. I still have problems with running the project locally.

**Comment by TejasQ** [comment]
Great! I'll do it. Let me know if you want to debug your local environment together and we can hop on a call some time this weekend or so. https://calendly.com/tejaskumar/pair-programming?back=1&month=2019-07

**Comment by march213** [comment]
@TejasQ It's awesome! Scheduled.
