### ISSUE TITLE
Only enable left/right buttons for tabs if there is not enough space

### ISSUE THREAD

**Issue by stereobooster** [contiamo/operational-ui#1123]
<img width="949" alt="Screenshot 2019-07-08 at 15 25 09" src="https://user-images.githubusercontent.com/179534/60813779-b119ca80-a194-11e9-9c2d-619172382eef.png">

At the moment left/right buttons are always enabled. It would be nice if they only _become enabled_ when there's more tabs than available space.

**Comment by kazionovm** [comment]
Hi, can I take it?

**Comment by TejasQ** [comment]
Yes!

**Comment by kazionovm** [comment]
@TejasQ I don't clearly understand what you want to do :)
As I understood: "when left panel tabs have a free space, the right arrow button must be disabled?"

![image](https://user-images.githubusercontent.com/38687326/61146979-f830f400-a4e3-11e9-8dc9-90fd8905ded2.png)

**Comment by stereobooster** [comment]
Buttons should be enabled only if div with tabs scrollable (horizontally). To do this you will need to get internal width of div and width of visible area, then you know that you need to enable one or two buttons depending on the situation, as well you need to track scroll position to enable disable one of the buttons if scroll in the given direction is not available. You can do those two tasks one by one, this way it would be easier e..g enable both button if there is scroll. And then implement code for disabling one of the buttons depending on the state of the scroll.

**Comment by kazionovm** [comment]
@TejasQ, @stereobooster  Hi guys, I am back and will help you with pleasure

**Comment by TejasQ** [comment]
Let's do it!

**Comment by stereobooster** [comment]
I need to fix this issue now, so I will take over this ticket. @kazionovm you can check implementation here https://github.com/contiamo/operational-ui/pull/1213/files. You're welcome to pickup any other issue in the tracker if you like it 👍
