### ISSUE TITLE
Add `outline` version to each button

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1126]
Let's add a boolean prop to `Button`, `outline`, that when true, gives the button the following appearance:

- White background color
- Whatever `color` prop is specified to becomes the border and text color

Kind of like

![image](https://user-images.githubusercontent.com/9947422/60972488-ae4edf00-a326-11e9-9034-321bd7e36f2b.png)
![image](https://user-images.githubusercontent.com/9947422/60972496-b149cf80-a326-11e9-8947-7d8ccf43767a.png)

Buttons without a `color` prop already look this way. 🤔

**Comment by rimildeyjsr** [comment]
@TejasQ - can I take this up?

**Comment by TejasQ** [comment]
Yes you can!

**Comment by rimildeyjsr** [comment]
@TejasQ - Hey Tejas, I have a working solution for this issue, but I need your help with one issue before I can raise a PR.

After adding the `outline` prop to the `<Button>`, I am getting an error on the demo, attaching the screenshot for it.

<img width="772" alt="Screenshot 2019-10-01 at 6 29 13 AM" src="https://user-images.githubusercontent.com/10229595/66020437-ae651200-e504-11e9-8ac7-fedcac0c5813.png">

I am not sure what I am doing wrong, and I tried googling the error as well but did not get any appropriate fix for this.

Code wise - I added `outline` to the button props and to the `BaseButton`. The major changes were to the `makeColors` function to create a white background and set border and text color to the input color prop when the outline is true.

`export const makeColors = (theme: OperationalStyleConstants, color: string, outline: boolean) => {
  const defaultColor = theme.color.white

  const backgroundColors: { [key: string]: string } = {
    grey: theme.color.background.light,
    warning: defaultColor,
  }

  const textColors: { [key: string]: string } = {
    grey: theme.color.text.action,
    warning: theme.color.error,
  }

  const borderColors: { [key: string]: string } = {
    ghost: "transparent",
  }

  const expandedColor = String(expandColor(theme, color));

  const backgroundColor = (outline && color) ? defaultColor : (backgroundColors[color] || expandedColor || defaultColor)

  const textColor = (outline && color) ? expandedColor : textColors[color] || readableTextColor(backgroundColor, [theme.color.text.default, theme.color.white])

  const borderColor = (outline && color) ? expandedColor : borderColors[color] || (isWhite(backgroundColor) ? theme.color.border.disabled : backgroundColor)

  return {
    background: backgroundColor,
    foreground: textColor,
    border: borderColor,
  }
}
`

Let me know if you need more information or clarification, I know I rambled on 😅

**Comment by TejasQ** [comment]
Oh wow! Thank you so much for coming back to this – but to be honest, 2 and a half months later (😅!) I'm not sure this is needed anymore. My apologies – we should've mentioned this earlier but we didn't think anyone was working on it.

**Comment by rimildeyjsr** [comment]
@TejasQ - hey no problem! honestly, I should have mentioned that I won't be able to pick this up for a long time after it got assigned to me!

I will pick up something more current from the issue list! 😃
