### ISSUE TITLE
Change type signature of the SimpleLink component

### ISSUE THREAD

**Issue by march213** [contiamo/operational-ui#1134]
Change type signature from:
```
const BaseSimpleLink = styled<"a" | "button">("button", {
  shouldForwardProp: prop => !["color_", "left_", "right_"].includes(prop),
 })
```

To:
```
const BaseSimpleLink = (styled<"a" | "button">).button``
```

The `.button` syntax automatically filters props and make code much cleaner.

**Comment by TejasQ** [comment]
If this works, then I don't see why we shouldn't do it. @stereobooster any thoughts?

**Comment by march213** [comment]
It doesn't work, I have an error:

![image](https://user-images.githubusercontent.com/8292471/61239733-994ec300-a70d-11e9-8864-ed0f61c4d3f5.png)


Maybe it is because the syntax is wrong, I'm currently working on it 🧐

**Comment by stereobooster** [comment]
Let me help you here a bit. What I would first is find the type definition. For example in IDE (in my case vscode) <kbd>cmd</kbd> + click on `styled`

<img width="766" alt="Screenshot 2019-07-15 at 22 39 16" src="https://user-images.githubusercontent.com/179534/61247462-6fb78b00-a751-11e9-91f0-db64946f3d65.png">

```ts
export default styled as CreateStyled<OperationalStyleConstants>
```

<kbd>cmd</kbd> + click on `CreateStyled`

```ts
export interface CreateStyled<Theme extends object = any>
  extends BaseCreateStyled<Theme>,
    StyledTags<Theme> {}
```
<kbd>cmd</kbd> + click on `CreateStyled`

```ts
export interface CreateStyled<Theme extends object = any> {
  <Tag extends React.ComponentType<any>, ExtraProps = {}>(
    tag: Tag,
    options?: StyledOptions
  ): CreateStyledComponentExtrinsic<Tag, ExtraProps, Theme>

  <Tag extends keyof JSXInEl, ExtraProps = {}>(
    tag: Tag,
    options?: StyledOptions
  ): CreateStyledComponentIntrinsic<Tag, ExtraProps, Theme>
}
```

as you can see param type here is `Tag` (`<Tag, ExtraProps>()`).

Let's see definition of `styled.button`:

```tsx
button: CreateStyledComponentIntrinsic<'button', {}, Theme>
```

and then:

```tsx
export interface CreateStyledComponentIntrinsic<
  Tag extends keyof JSXInEl,
  ExtraProps,
  Theme extends object
> extends CreateStyledComponentBase<JSXInEl[Tag], ExtraProps, Theme> {}
```

and then:

```tsx
export interface CreateStyledComponentBase<
  InnerProps,
  ExtraProps,
  Theme extends object
> {
  <
    StyleProps extends Omit<
      Overwrapped<InnerProps, StyleProps>,
      ReactClassPropKeys
    > = Omit<InnerProps & ExtraProps, ReactClassPropKeys>
  >(
    ...styles: Array<Interpolation<WithTheme<StyleProps, Theme>>>
  ): StyledComponent<InnerProps, StyleProps, Theme>
  <
    StyleProps extends Omit<
      Overwrapped<InnerProps, StyleProps>,
      ReactClassPropKeys
    > = Omit<InnerProps & ExtraProps, ReactClassPropKeys>
  >(
    template: TemplateStringsArray,
    ...styles: Array<Interpolation<WithTheme<StyleProps, Theme>>>
  ): StyledComponent<InnerProps, StyleProps, Theme>
}
```

as you can see param type here is `StyleProps` (`<StyleProps>()`).

e.g. `styled()` and `styled.button` expect different type param so initially proposed code `(styled<"a" | "button">).button` won't work.

**Comment by stereobooster** [comment]
So the question is should we try to overcome this limitation of built in types and trick TS to treat `styled.button` as `CreateStyledComponentIntrinsic<'button', {}, Theme> | CreateStyledComponentIntrinsic<'a', {}, Theme>` or should we simply use `shouldForwardProp`? 

@march213 what do you think?

**Comment by march213** [comment]
For my personal taste, I'll choose to use `shouldForwardProp` because it's more clear in this situation.

**Comment by TejasQ** [comment]
Great! So shall we close this issue then?
