### ISSUE TITLE
Page title should be a ReactNode

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1148]
Currently, `Page` only accepts `string`s as `title`, but sometimes, we might want more customization. Let's allow `ReactNode`s here instead.

https://github.com/contiamo/operational-ui/blob/033368547c3c904c6484aa6d5031c1f1d5137e54/src/Page/Page.tsx#L16

**Comment by solankivj94** [comment]
@TejasQ  - may I work on this?

**Comment by solankivj94** [comment]
Oops! change have already been made.

**Comment by TejasQ** [comment]
Oh, right. Thanks for noticing. Will close this. Sorry for the late response. ❤️
