### ISSUE TITLE
Add "backButton" label to `Page`

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1149]
It would be nice if `Page` had a back button as an optional prop, whose label is the value of the prop and it automatically goes back.

Kind of like this:

![image](https://user-images.githubusercontent.com/9947422/61380338-778a4300-a8a9-11e9-9d39-51c74d255bd2.png)

**Comment by rimildeyjsr** [comment]
@TejasQ - can I work on this? 🙂

**Comment by TejasQ** [comment]
YES! WOOO

**Comment by TejasQ** [comment]
@rimildeyjsr any updates here? To be honest, the `Page`'s title prop is already a `React.ReactNode`, so people could already add this back button in userland. If you haven't started on this yet, I'm not sure we'll need to spend time on this.

**Comment by rimildeyjsr** [comment]
@TejasQ - no i haven't started working, will pick up something else! :)
