### ISSUE TITLE
Tree focus

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1166]
A sibling to #1085 – a [tree item](https://github.com/contiamo/operational-ui/blob/master/src/Tree/TreeItem.tsx) would look nicer if it had a blue focused state like so:

![image](https://user-images.githubusercontent.com/9947422/62038124-6ddfd400-b1f5-11e9-8e14-cc1c5a425f85.png)

**Comment by Life-Hex** [comment]
I'll take this!

Now, to figure my way around it.

**Comment by TejasQ** [comment]
Let me know if you need any help!

**Comment by stereobooster** [comment]
It is resolved by https://github.com/contiamo/operational-ui/pull/1301
