### ISSUE TITLE
Playground cursor jumps unexpectedly after resize

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#184]
After a resize or expand, playground cursor can jump from the middle of a line to the beginning of the next line when only a right arrow key is pressed.

**Comment by TejasQ** [comment]
Is this still a thing?

**Comment by peterszerzo** [comment]
@TejasQ it is - as soon as component-playground implements an `onChange` prop we can use to keep the input field state in the parent, we can force rerender the playground on expand and make the problem go away.
