### ISSUE TITLE
Process flow case number four blocks the Sidebar menu

### ISSUE THREAD

**Issue by Angarsk8** [Contiamo/operational-ui#227]
## Description

Process flow case number four blocks the `Sidebar` navigation menu. 

## Steps

1. Visit https://ui.contiamo.com/visualizations/process-flow/cases/case04
2. Notice how the Process Flow visualization  blocks the Sidebar menu after completing the test case.

**Expected Result**: Test case renders properly and doesn't block Sidebar menu.

## Screenshots

![image](https://user-images.githubusercontent.com/11448559/32652295-115af4be-c604-11e7-9570-e27352cabcb0.png)

![image](https://user-images.githubusercontent.com/11448559/32652250-f347aba2-c603-11e7-8332-2780260a207d.png)

**Comment by peterszerzo** [comment]
@Contiamo/frontend would someone be available to pair with me on this one on Wednesday? It's a finicky flexbox issue I've attempted twice already.

**Comment by TejasQ** [comment]
🎉
