### ISSUE TITLE
Info Messages

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/operational-ui#230]
I know this is on the roadmap soon, but I'd like to officially open a request for it via issue. It would be nice to have something like this, configurable with theme colors:

![image](https://user-images.githubusercontent.com/9947422/32733103-b4c216a0-c88e-11e7-9668-9bee371c3390.png)

![image](https://user-images.githubusercontent.com/9947422/32733147-d039510a-c88e-11e7-9d67-43fed7de3549.png)

**Comment by peterszerzo** [comment]
Nice, we should get these in soon then. Are you thinking something along flash messages at a fixed place on the interface (top center, bottom right), or placeable wherever?

**Comment by TejasQ** [comment]
Yes! That way they're easier to animate!

**Comment by TejasQ** [comment]
@peterszerzo this should add to our current ongoing Message component discussion.

**Comment by peterszerzo** [comment]
I'd close this for now - https://ui.contiamo.com/components/messages/ are working, and I think we should take our time making some messaging system on top of it.
