### ISSUE TITLE
Use tabular instead of proportional numbers for visualizations / labels / breakdowns.

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#242]
It'd be nice to define a global font style that can easily be used everywhere to display numbers.

In tables, labels, breakdowns etc. tabular numbers will look better as numbers with the same number of digits will take up the same space.

In the past I've set these styles to achieve this - however I'm sure you guys can improve on that:

```css
font-family: "Lato", monospace;
font-feature-settings: "tnum";
```

There is also a [font-variant](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant ) property which supports a `tabular-nums` value.

**Comment by peterszerzo** [comment]
I'll look into this towards the end of the week.

**Comment by peterszerzo** [comment]
@micha-f I feel like the value for the monospaced font should be specified in the theme (with a good sensible default). And once it's there, it feels more natural to set it in the glamorous components as `fontFamily: theme.fonts.monospaced` in the `@operational/components` wherever we're sure we're displaying numbers. Apps using operational packages can do the same - and then we can avoid relying on CSS properties that are not so widely used. What do you think?

**Comment by micha-f** [comment]
@peterszerzo Sounds good. As long as we can have proper tabular numbers where we need them, I'm happy :)

**Comment by micha-f** [comment]
@peterszerzo we should also make sure we use tabular numbers in the labels for visualizations, the axis ticks etc.
I'll create a new ticket for that.

**Comment by peterszerzo** [comment]
@micha-f cool, just reopened!

**Comment by peterszerzo** [comment]
Actually, never mind, you already have it.
