### ISSUE TITLE
Re-evaluate theme colors

### ISSUE THREAD

**Issue by peterszerzo** [Contiamo/operational-ui#255]
After a fair bit of use, I find color names and paths in the theme quite verbose and discouraging, often finding myself thinking `screw this, I'll just hardcode it`. I am worried users will feel the same way, making the library hard to popularize later. I've had a chance to look at a few ui libs (material, ant), and notice that they mesh usage and palette colors into a single object. Suggesting the following changes:

`theme.colors.usage.bodyBackground -> theme.colors.background *`
`theme.colors.usage.bodyText -> theme.colors.regularText *`
`theme.colors.usage.emphasizedText -> theme.colors.emphasizedText`
`theme.colors.usage.lightText -> theme.colors.lightText`
`theme.colors.usage.link -> theme.colors.linkText *`
`theme.colors.usage.cardBackground -> theme.colors.cardBackground`
`theme.colors.usage.sideNavigationBackground -> theme.colors.sidenavBackground`
`theme.colors.usage.contentSeparatorLine -> theme.colors.separator`
`theme.colors.usage.subContentSeparatorLine -> theme.colors.secondarySeparator`
`* name changes in addition to flattening `usage` and `palette` fields`

`theme.colors.palette.info -> theme.colors.info`
`theme.colors.palette.success -> theme.colors.success`
`theme.colors.palette.warning -> theme.colors.warning`
`theme.colors.palette.error -> theme.colors.error`
(same with black, white, and greys - but to be consistent with American spelling, I'd call them grays)

Add `theme.colors.brand` for companies that have a primary brand color that doesn't fit into info, success, error etc (Telekom's magenta).

**Comment by peterszerzo** [comment]
As a historical note, I should add that the reason we split usage and pattern colors up back in the day was to encourage some re-use between them. Unfortunately, I don't see the encouragement working effective after starting a few client projects with the library.

**Comment by micha-f** [comment]
@peterszerzo That makes a lot of sense, let's do this!

**Comment by TejasQ** [comment]
I agree. Also, a _giant_ +1 for being sensitive to thinks that make you feel like `screw it, I'll just hardcode it` and trying to improve them. I am convinced this is one of the bigger reasons our component library will be (and already is) amazing. 🎉
