### ISSUE TITLE
Should we keep PlusChip?

### ISSUE THREAD

**Issue by peterszerzo** [Contiamo/operational-ui#263]
I don't think it makes sense to keep the `PlusChip` component around, since it is mostly used with `Chip`'s, and its functionality can be incorporated into that component like the way `Filter`'s currently work:

![screen shot 2018-01-03 at 10 24 32](https://user-images.githubusercontent.com/6738398/34515039-9a261332-f070-11e7-9683-432120a97f88.png)

We could extend the `Chip`'s to only display the symbols if a label is not present, and this would guarantee that the plus sign is always the same size as the neighboring chips.

**Comment by peterszerzo** [comment]
@TejasQ any thoughts on this?

**Comment by TejasQ** [comment]
I agree with you: let's remove PlusChip.

**Comment by TejasQ** [comment]
🎉
