### ISSUE TITLE
Spinner center has background that overlays poorly

### ISSUE THREAD

**Issue by peterszerzo** [Contiamo/operational-ui#277]
In the image below (`Auth` block), the white background used to hide the inner part of the spinner's circle hides part of the underlying input field's border. This makes overlay spinners tricky to use.

<img width="574" alt="screen shot 2018-01-10 at 4 46 28 pm" src="https://user-images.githubusercontent.com/6738398/34781375-f2ed9b4c-f625-11e7-83c8-6852c134127e.png">

@TejasQ do you know a fix for it without changing how the spinner is made? Or shall I just go ahead and replace it with an SVG?

**Comment by TejasQ** [comment]
The way the spinner works is basically white smaller circle on large blue circle. _Large blue *circle*_, not large blue _stroke_, so it's pretty much unfixable. I say we go SVG.
