### ISSUE TITLE
<OperationalUI /> only accepts one child

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/operational-ui#284]
`<OperationalUI />` only accepts one child, and cannot contain multiple children. **Please make this explicit in the README, and log a proper error if the following is attempted:**

```javascript
<OperationalUI>
    <div>foo</div>
    <MyComponent bar={baz} />
</OperationalUI>
```

**Comment by peterszerzo** [comment]
I love it - thanks for suggesting this, @TejasQ, this will be a huge improvement (eta tomorrow morning)
