### ISSUE TITLE
Standard header

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/operational-ui#285]
As people pick up and learn Operational, a fun starter project could be to build a page that looks similar to the showcase in terms of layout: with a `Sidenav` and a `Header`.

What's really weird, is that the exported `Header` from `@operational/components` does _not_ look as expected out of the box: I would expect a proper header, as on the showcase, upon direct inclusion of `<Header />`.

Turns out, [it's styled specifically that way _just for the showcase_](https://github.com/Contiamo/operational-ui/blob/master/packages/showcase/components/Header.js#L24-L29). To me, this does not make sense. Can we adjust the exported `Header` component to be this way?

**Comment by peterszerzo** [comment]
@TejasQ do you mean moving those styles from showcase code directly to `components/Header`? If so, makes perfect sense, should have been that way a long time ago. Will get on it very soon!
