### ISSUE TITLE
OperationalUI Context

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#294]
Now that we have the `OperationalUI` wrapper component, we should add some [context functionality](reactjs.org/docs/context.html) to it. I'd start with `windowWidth`, `windowHeight` and `mouseX` and `mouseY`.

The concrete use-case is overflow checking for tooltips + allowing a stick-to-mouse option, which allows an easy-to-maintain `withTooltip` wrapper. If there are lots of tooltips on the page, having all this contextual info in a single place will help performance (and the event listeners can get some nice throttling to help with that).

Thoughts?

**Comment by TejasQ** [comment]
My initial thought is that we ought to _be careful_ how we handle `context` and make sure we _properly_ understand it before implementing features that interact with it. 🤔

**Comment by peterszerzo** [comment]
I'll do a quick 30-minute experiment PR and see how it feels.

**Comment by peterszerzo** [comment]
Some ideas from Pantheon:

```
<Layout>
  {ctx => (
    <Button onClick={() => {
      ctx.pushMessage("Something happened successfully")
    }>Create a generic flash message</Button>
  )}
</Layout>
```

I wonder about the syntax here. Should we send strings? `{ body: "", theme: "warning" | "error" | "info" }` objects? It is super tempting to also give this some functionality, but it will be brittle: if we send it any kind of `onRetry` component that operates within the component the message was pushed from, there is no guarantee that said component will still be around when the thing is called. That sounds like lots of `trying to update an unmounted component. This is a no-op` errors..

Thoughts?

**Comment by TejasQ** [comment]
I think it would be helpful to visualize possible code with a more complex component:

```jsx
<Layout>
  <div>
    Hi, I'm a div and stuff
    <OtherComponent foo={bar} />
  </div>
</Layout>
```

Meanwhile, in `OtherComponent.jsx`,

```jsx
class OtherComponent extends React.Component {
  componentDidMount() {
    // ok but I also want to push a message now, but I can't :(
  }
  render() {
    return (<div>
      Hi, I'm the OtherComponent, dood!
      <ContextConsumer>
        {ctx => <button onClick={ctx.pushMessage("I LIKE TO EAT DIRT OKAY, DON'T JUDGE ME!")} />
      </ContextConsumer>
    </div>)
  }
}
```

Given the above samples, I have the following thoughts:
- Sending strings is fine. We can add retry/dismiss/whatever callbacks as needed later, _if needed_. I'm a fan of keeping things minimal and scaling as necessary.
- What if we want to use `pushMessage` in lifecycle methods?
