### ISSUE TITLE
Header is 52px wide? Why?

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/operational-ui#295]
[I'm having a hard time seeing the use-case and how this makes sense](https://github.com/Contiamo/operational-ui/blob/master/packages/components/src/Header.tsx#L16).

Conventionally, our `Header`s _everywhere_ are fullwidth. 🤔

**Comment by peterszerzo** [comment]
Yepp, that should go out - it looks like some legacy leftover from when its container was flexed and the flex direction was vertical. That's why it never showed up as a layout bug.

Thanks for the catch :)
