### ISSUE TITLE
Records improperly styled

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/operational-ui#299]
![wat](https://user-images.githubusercontent.com/9947422/35441195-db083c6a-02a2-11e8-9f9c-fad87b731188.gif)

- There is no background color (a la `Card`s)
  - are they supposed to go inside a `<Card />`? This is not immediately clear to a consumer.

- Weird behavior with `RecordSummary` when its expanded (See GIF)
- Can we please rename `RecordSummary` -> `RecordHeader` to keep consistency with `Card`'s `CardHeader`?

**Comment by peterszerzo** [comment]
The idea is to put `<Heading1/>`s inside the header. We can make this behavior more robust by automatically styling the summary's contents as heading1's, so it works for a plain string.

As you say, they are supposed to go into a card, but then again, everything is supposed to go into a card. I wouldn't add specific instructions for that. As our docs pages expand, this will get clearer to the user as well. Stay tuned.

`<RecordHeader>` is a great rename!

**Comment by TejasQ** [comment]
Also,

![image](https://user-images.githubusercontent.com/9947422/35441759-06972df8-02a5-11e8-96df-09f1ed1cac33.png)

They do not look as expected inside a card.

**Comment by TejasQ** [comment]
@peterszerzo, mind if I take this one?

**Comment by peterszerzo** [comment]
Go for it :)
