### ISSUE TITLE
Proposal: Prop on <Button /> to specify outline/full color

### ISSUE THREAD

**Issue by TejasQ** [Contiamo/operational-ui#301]
This would be really helpful for button sets containing multiple buttons, and _one_ being the primary action, kind of like this:

![image](https://user-images.githubusercontent.com/9947422/35442338-35f71c96-02a7-11e8-8d4b-e3fb1a08957b.png)

We also see this in GitHub

![image](https://user-images.githubusercontent.com/9947422/35442362-4a9c2a60-02a7-11e8-8b9b-0a695d091853.png)

The API I'm imagining is simple:

```jsx
<Button outline>HOLA MUNDO</Button>
<Button>PRIMARY ACTION</Button>
```

Assuming `colors.primary` is green, the button containing `HOLA MUNDO` will have a green outline, next to the full-color `PRIMARY ACTION`

```jsx
<Button outline color="gray30">hi</Button>
```

would give you a gray30-outline-button.

Does this make sense?

**Comment by peterszerzo** [comment]
I don't think this is a good direction - a thin outline is too subtle a clue to make buttons stand out, and is too close visually to the shape of a focused input field. I think button borders should keep being set automatically, to a color very close in hue/value to the background color.

**Comment by TejasQ** [comment]
Okay. ¯\_(ツ)_/¯
