### ISSUE TITLE
Button spinner

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#315]
Most components have async interactions: buttons do something async on click (like requests), autocomplete/select components could do fetches on filter, going forward, _table_ blocks could use filtering, the login block, etc.

It might be a good idea to expose a component that creates and gives out a spinner to use inside of any old component in the event one is needed, to signal background activity.

Here's a [sample implementation](https://codesandbox.io/s/moojrr58mx) that I threw together of what this could look like. Thoughts?

## Use Case
There is a use case in the Labs UI for this or something like this, for example, when one clicks "Deploy" on a bundle: it fires off a request. It wouldbe nice to have the button disabled with a status indicator on the button.

![image](https://user-images.githubusercontent.com/9947422/36538205-c78dbc06-17d2-11e8-9c3f-198915a90678.png)

**Comment by peterszerzo** [comment]
Great direction! Implementation-wise, I think this is something components should implement internally, and expose the same `loading` prop to the outside. Buttons should probably render the spinner on the right side of the text without covering it, and whole cards should probably, more often than not, use the loader strip instead of the spinner.

My concern with exporting a `WithSpinner` from the library would be that it'd encourage misuse (or use with a suboptimal UX outcome). Having it around internally, however, is really nice - we can have higher-order components next to the `withLabel` one that we already have.

Would you like to take on the implementation, @TejasQ?

**Comment by TejasQ** [comment]
I'd love to implement this. I prefer the [function as children](https://reactpatterns.com/#function-as-children) pattern as opposed to the HOC pattern though, because it avoids prop collision and is more clear about _what data goes where_, and is more idiomatic: it can be represented as JSX without having to call a HOC factory function on a component and _then_ representing _that_ as JSX:

```jsx
const MyWrappedComp = withSpinner(MyComp)
<MyWrappedComp />
```

vs

```jsx
<MyWrapperComp>
  {thing => <MyComp />}
  {/* Look mom, I can even put OTHER CHILDREN HERE WOW */}
</MyWrapperComp>
```

For the reasons state above, am I okay to use this pattern in the implementation?

**Comment by peterszerzo** [comment]
Since it stays internal, I don't mind. It'll be cool to see which of the two approaches works better for us.

Adding render callbacks in the public API is something I'd like to avoid until we have so many repetitive UI features that individual components' props list get unwieldily long.

**Comment by peterszerzo** [comment]
@TejasQ per discussion in https://github.com/contiamo/operational-ui/pull/352, I think the consensus is starting to be that we avoid a generalized loader and prefer simple composition:

```
<Card>
  <Progress />
  <Content>
</Card>
```

There should be a few exceptions, though, in my opinion. A `<Button loading>Do this thing</Button>` pattern with an embedded spinner sounds like something we should have. Shall we rename this issue for just that functionality, carry it through, and tackle new specific needs as they arise?

**Comment by TejasQ** [comment]
Sounds good!

**Comment by fabien0102** [comment]
Why not:

```js
<Card loading={this.state.loading}><Content /></Card>
```

It's easier to implement as consumer of the lib as we just need to pass the state to the props instead of add an "ugly". And I think that the API is also more clear with a `loading` props.

```js
<Card>
  {this.state.loading && <Progress />}
  <Content>
</Card>
```

**Comment by peterszerzo** [comment]
I think the idea here is that we limit the number of components that support the `loading` functionality. Having it available everywhere will lead to overuse and a clunky UI - github or basecamp and the likes has it pretty much at the top and that's it.

We had identified button spinners as an exception to this rule.

**Comment by micha-f** [comment]
This comment does not concern implementation (!), it's more of a general thought on UX.

I agree with the github / basecamp example as a general good practice.

From my experience if a page displays only one main thing (e.g. a list of data sources or an individual data source), it makes a lot of sense to only have a single progress bar at the very top. If making this request fails, the page essentially "failed".

If we have cards or components that fetch and display content independently (as in the explore view or a potential dashboard view with many widgets), it does make sense to implement a loading and error state that is visually "local" to that component. The idea here is to clearly show to the user which component is currently fetching and to "contain" the error if there is one.

**Comment by fabien0102** [comment]
For the general thougt on UX, I also prefer to have little spinners on buttons. To take an example, on my current implementation in labs, I can request to sync and to deploy my bundle in the same time. With a little loading button state, I can do the both in same time and do something else waiting for the response. (and it's really clear for the final user)

It can be also very useful if we decide to implement the last React suspense or if have a part really heavy part to load. So you can have only some part loaded and the user can easily understand which one.

For the errors, a simple implementation is to add the ability to stack errors in the global error layout (with a timeout)

**Comment by TejasQ** [comment]
I'd support a loading prop _only on components that can have potential loading state_ a la buttons, cards that is _merely_ sugar for the same component with a spinner/progress component inside. If we can't use spinners/progress inside, we ought to question the usability of those components.
