### ISSUE TITLE
<Input /> is wrapped in a div

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#321]
Is this intended behavior? It could be a little bit surprising to consumers: "I want an input, but why is there automatically a _forced div around it?!"_

Is this something we can/should do differently?

**Comment by TejasQ** [comment]
Definitely like this approach because then we can even omit the `for` prop on `label`: it _knows_ it's the label for the `input` that it contains. 👍 

I actually don't see a real use-case for HOCs or a container label with a render callback. I have to ask: why can't we just put a `<label>` inside of `Input` and `Select`? I don't think we have _that_ many input elements where it would be a scale problem... 

Moreover, we could _only_ render a containing `label` if there is a `label` prop supplied...

**Comment by peterszerzo** [comment]
I agree with all the above - so the plan of attack is:
* take out the HOC and add individual implementations.
* if no `label` prop is specified, render just a naked `<input>` tag.
* otherwise, use the markup above and be done with it.
* add a `condensed` prop to decrease padding on the input.

Did I get that all right?

**Comment by TejasQ** [comment]
Sounds incredible. 

It may be a good idea as well to add an `inline` prop that renders the input _completely naked_: no bounding box, no nothing, just a field of manipulatable text that can be contained in whatever one may desire: like a `CardHeader` or a custom input-box-looking `div`. What do you think?

**Comment by peterszerzo** [comment]
That's what would happen if you give it no label (second bullet point above), or do you mean something different?

**Comment by TejasQ** [comment]
I mean something different:

- no label => proper input, boxed, _clearly_ identifiable as an input field
- label => same as above but with a geometrically fixed label
- inline => completely transparent: no box, no decoration at all, decoratable by a containing component

**Comment by peterszerzo** [comment]
So you mean some kind of `locked` view that's the same size as the input, but doesn't look like one? I think it needs a more descriptive name, less people would think about `display: inline`..

**Comment by TejasQ** [comment]
Sure. I'm up for discussing names, but I'd love for an input to be able to look like this and then wrap it with whatever boxing-input-style-container I want.

![Demo](https://user-images.githubusercontent.com/9947422/36723936-e8d8a582-1bb1-11e8-8bcc-ae476f34a457.gif)

**Comment by peterszerzo** [comment]
Aside from concerns of this becoming overly flexible and inconsistent, I think it needs to be visually obvious for the user that they're editing right now - otherwise, editable stuff is impossible to find or identify `=>` in a blown-up scenario, the app would turn into a point-and-click game. The reason I'm suggesting the `locked` prop is that then you can just unlock it on click, and turn it into an input field with proper focus effect, but the same height so nothing jumps around. And this overhead of setting it up should discourage overly frequent use, which I think we should avoid.

**Comment by TejasQ** [comment]
I actually like that quite nicely.

**Comment by peterszerzo** [comment]
In the `<CardHeader>` for instance, I'd just do `<CardHeader>{this.state.isUnlocked ? <Input value={this.props.editedTitle} condensed /> : this.props.editedTitle}</CardHeader>`, so you either get a properly styled header, or a standard-ly styled input.

I know I'm suggesting the exact opposite of WYSIWYG - I just think that that stuff is really hard to pull off, especially given our resources.

**Comment by TejasQ** [comment]
And the `condensed` prop would not mess around and cause height-jumping? Can we guarantee that?

**Comment by peterszerzo** [comment]
If you toggle `condensed`, the height should jump. But the implementation could guarantee that if you jump between `<Input condensed locked />` and `<Input condensed />`, or between `<Input locked />` and `<Input />`, then the height stays the same. 1px here and there would probably happen in some browsers, but it wouldn't be the end of the world. Would this work for your use-case?

**Comment by TejasQ** [comment]
Yes.

**Comment by TejasQ** [comment]
Are we sure about `condensed locked` though? Two props?

**Comment by peterszerzo** [comment]
Long story short, I think they have pretty clearly separate responsibilities, and I'm not sure right now which one will be worth having around/commonly used.

I have a feeling `condensed` would come up pretty often as space is something we tend to be frugal with, and we already have it for buttons so it's easy to learn/remember (could be a good idea to set up a `/common-props` page. As for `locked`, I'd count it as an experimental feature. I'm not sure how often we'll need it, or if it's a pattern that'll stick at all (as per `<CardHeader/>` example above, it's not so difficult to go around it).

Do you see a better way?

**Comment by TejasQ** [comment]
Nope. I like it. Glad we thought it through.

**Comment by peterszerzo** [comment]
Yes, me too, super good discussion.
