### ISSUE TITLE
Remove `React.SFC` type annotations?

### ISSUE THREAD

**Issue by micha-f** [Contiamo/operational-ui#333]
Are these `React.SFC` type annotations required?
Everything seems to be working fine without them.

```typescript
//ButtonGroup.tsx
const ButtonGroup: React.SFC<Props> = ...
```

**Comment by peterszerzo** [comment]
Good point, @micha-f, they are redundant type annotations, and we stopped doing them for new components with the exception of the ones that are exported with a `withTheme` HOC, where the type casting is necessary. I'll get these removed.
