### ISSUE TITLE
Replace abstract classes in visualizations through interface + mixins

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#334]
I'm not a big fan of these abstract classes: 
- it's not a common pattern in the JS world
- it's easy to end up with implementations in the abstract classes that deal with all sorts of special requirements by subclasses. We then essentially move all the individual implementations into a single implementation with branches

Maybe we can use an interface to define what a certain Renderer, Visualization etc. is supposed to implement and leave the decision on how to implement the functionality to the concrete class.
- In some cases we might be able to refactor abstract classes to get rid of the 2-3 abstract methods they have. Then they no longer need to be abstract.
- In some cases we might be able to some stateless helper functions to share code
- In some cases we might be able to get rid of abstract classes by just a little bit of code duplication - which would be worth it.

**Comment by ImogenF** [comment]
Makes complete sense. And it would be nice to get rid the viz code structure right before I port any more visualizations over. I'll start looking at that on Monday, if nothing urgent comes up in the meantime.

**Comment by micha-f** [comment]
@peterszerzo also wanted to tackle porting a visualization over. Might make sense to look at this together :)

**Comment by peterszerzo** [comment]
@ImogenF was this issue taken care of in #357?

**Comment by ImogenF** [comment]
@peterszerzo Yup!
