### ISSUE TITLE
Can we improve on the currently gray background for code snippets?

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#336]
Can we use a more friendly color? Also, we can probably improve the code syntax highlighting (for static snippets).

![image](https://user-images.githubusercontent.com/200647/36895909-eb3370ee-1e10-11e8-8b42-1362566ba7d0.png)

**Comment by peterszerzo** [comment]
I'd vouch for integrating playgrounds and static snippets so they look exactly the same - then we can throw away a bunch of code.

**Comment by micha-f** [comment]
But wouldn't that lead the user to think they could actually edit the code and see the output change?

**Comment by peterszerzo** [comment]
Then we can just make it so they're able to do that.

**Comment by micha-f** [comment]
Can we also adjust the theme for the playground code editor in that case? I think we tried out a light background (light blueish) and it looked nicer. Alternatively a light beige could work, too?
