### ISSUE TITLE
Reduce number of font-sizes

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#337]
Let's reduce the number of different font-sizes and go with the default font-size unless there are very good reasons not to.

This applies to 
- InfoTiles (value)
- Records
- Timeline

**Comment by peterszerzo** [comment]
There's only two font sizes total, and I think we have good reasons to have them around for these components in order to keep a sensible hierarchy. Removing the bolds would help make it a bit simpler, though.

**Comment by peterszerzo** [comment]
Closing this for now. With #347, we'll see fewer bold fonts and borders in the interface in general, which will help make things look cleaner, as well as more compact and more uniform. If we still think larger font sizes should go away then, let's re-open and discuss.
