### ISSUE TITLE
DatePicker: click on caret icon does not open the picker

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#343]
When you click on the caret, nothing happens.

![image](https://user-images.githubusercontent.com/200647/37043928-51015cf2-2162-11e8-846a-ed6184914d88.png)

**Comment by micha-f** [comment]
Also, once closed, the datepicker should not open again when "ESC" is pressed. Right now I can toggle open / close with ESC.

**Comment by peterszerzo** [comment]
@micha-f thanks for reporting! What browser/OS do you see the caret icon issue? I can't seem to reproduce it on Chrome, Firefox and Safari.

The keyboard fix is in the referenced PR.

**Comment by micha-f** [comment]
Sorry, caret issue has been fixed before.
