### ISSUE TITLE
Remove components

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#375]
A few components evolved over the past few months to lose responsibilities to other components or custom implementations, and ended up doing too little or get forgotten. This increases our API surface area to the confusion of the developer and adds maintainability workload. This issue is a discussion point to trim things down a bit.

## Color picker

The color picker module simply wraps another library, and doesn't fit into our design. I honestly think the project will be more marketable if we removed it altogether.

It would be cool to conceive a color picker that is maybe a bit more opinionated (chooses only among theme colors for example). That could be used later to e.g. customize how parts of a UI look for different projects or tags, the way twitter would do it.

## Header

Right now, it is basically a 52px tall white strip with `theme.shadows.card` and `justifyContent: space-between` applied to it. Is that enough responsibility to justify a separate component, or can we give it some more? (side note: ant design doesn't have one, and `material-ui`'s `<AppBar />` is much more opinionated, taking a title string and icon names)

The alternative would be to just export the `52px` constant value through theme so that folks can make headers that check out in height with the side navigation items, and never use an explicit `Header` component.

## Upload

I think we should keep moving towards being more presentational, and remove all the `async` stuff. Can the header-setting, file reading stuff go into the rest client? I can totally see a small component with an input type="file" + drop zone rendered here (or in blocks), with a progress prop that would take care of the loading state.

Thoughts?

**Comment by micha-f** [comment]
Good points. Agree with the color picker. Regarding the header I'd say making it more opinionated would be fine. I would not remove it. I'm all for striping the handling logic from the upload component.
