### ISSUE TITLE
Input locked state, validation and hint

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#377]
Inputs need some features:
* locked for editing with an unlock feature
* hint element in a form of a question mark icon with a tooltip explaining e.g. why the input field is locked
* validation error, giving it some red borders.

```
<Input
  error="Field must be unique"
  locked={this.state.locked}
  onUnlock={() => this.setState(prevState => ({ locked: false }))
  hint="You cannot edit this field because so and so"
/>
```

Can I get some thoughts on the API @TejasQ? Can these fields be condensed or restructured? Or, since I'm in a showboaty mood: can we make them more orthogonal 🤓?

**Comment by peterszerzo** [comment]
`onUnlock` is necessary because the user might want to unlock a form element for editing in the case when we actually don't want to make editing impossible, just want to deliberately add an extra step so the form feels safer. Resource names in pantheon are an example, because renaming those can break PSL code. You're right in that it should be `onToggleLockedState` or something so it can go both ways.

I think `error` and `hint` should be different features, and should look different visually. I'm thinking of porting over the help tooltip from here: https://peterszerzo.github.io/elm-natural-ui/#input to display explanations to an input field that doesn't fit inside the label (you can't edit this because..). Errors, on the other hand, should color things red and make it look all scary.

**Comment by TejasQ** [comment]
I agree with having `onUnlock` serve as a lifecycle hook for `Input` and the two-way `onLockStateChanged` or something along those lines.

How about if `isValid` makes things red and look all scary while `hint` displays an appropriate hint to the user: if there's an error, help them out. If there's _no_ error, _also_ help them out: "Maximum 100 character limit" or something?

**Comment by peterszerzo** [comment]
How would we handle displaying the error message in that case? I would not add that into the hint - for some fields, a hint might be something like `Careful when you edit this because...`, whereas an error would be like `Name already exists`, and would show only some of the time. Would an `error : string | null` prop be too cryptic for users?

**Comment by TejasQ** [comment]
Ah, I see. I think in that case it makes sense to have an optional error prop. `error?: string`
