### ISSUE TITLE
Theme spacing should be 16px

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#380]
This issue concerns [this](https://github.com/contiamo/operational-ui/blob/master/packages/components/src/Header.tsx#L22). 

It causes mismatches with alignments when laying out a page. Here's an example:
![image](https://user-images.githubusercontent.com/9947422/38556654-b03390ae-3cca-11e8-8e5d-c39320be1a6e.png)

Thoughts?

**Comment by peterszerzo** [comment]
I'd say it'd look crammed otherwise - just bump the padding of the section below.

**Comment by TejasQ** [comment]
But – as a user of the library, I'm relying on `theme.spacing` in the section below... and in this case, `theme.spacing` offsets things and causes inconsistencies in my app. 

I would expect `theme.spacing` to enforce consistency.

**Comment by peterszerzo** [comment]
You are right, changing it to `16px` will make sense at this point. It will break a lot of things, but I think it'll be worth going through them. I'll tackle that once the trimmed down showcase page is ready.
