### ISSUE TITLE
Improvements from building UIs

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#385]
In building our internal tools at Contiamo, we're finding ways in which some components work better and improving them _on the fly_ in our UIs. This is an aggregation of these improvements to be grafted into Operational as a whole.

## Improvements
- [x] All links in `Sidenav` need to be full-width blocks that inherit styles from the document and aren't underlined.
- [x] Padding needs to be standardized. (See #380)
- [x] `Table`
  - [x] improved `tr` padding as in Pantheon UI.
  - [x] no border by default
  - [x] **code smell**: `tr` _and_ `td` have paddings... why? @peterszerzo 
  - [x] need provision/prop for alternating row colors for readability
  - ~~Propagate css prop to underlying table (maybe?)~~
- [x] ~~`PageContent` from PantheonUI possibly needs to be included.~~
- [x] `TextArea` from PantheonUI (SEPARATE ISSUE/PR)
- [x] `Person` (maybe called `Avatar`?) from Labs (SEPARATE ISSUE/PR)
  - @tejasq will implement

- [x] Create component for this thing (SEPARATE ISSUE/PR)
  - ![image](https://user-images.githubusercontent.com/9947422/38668011-61ce597e-3e43-11e8-852d-96925926ac92.png)
- [x] `Tabs` must support a `css` prop in order to allow styling extensions.
- [x] Heading types need explicit margins because browsers have styles that can mess things up
  - ![image](https://user-images.githubusercontent.com/9947422/38671315-5d43f46a-3e4b-11e8-8fef-6ac4275efcd6.png) (SEPARATE ISSUE/PR)
- ... more to come. Feel free to edit this post and add more.

**Comment by TejasQ** [comment]
I feel calling `Person` `Avatar` may not be fully true because the way I see it, a `Person` has a name alongside an `Avatar`, while an `Avatar` is just a round photo/initials.

**Comment by micha-f** [comment]
I feel that the contiamo-next sidebar looks better than the pantheon UI sidebar. Not sure which one is "standard" operational UI

**Comment by peterszerzo** [comment]
@micha-f they're pretty much the same - the only additions are the differently colored top bit and the flyout product switcher menu.

**Comment by micha-f** [comment]
@peterszerzo Interesting. Thought the font size for contiamo-next was smaller (but it's the same). The width of the sidebar is different - I prefer the contiamo-next one.

**Comment by peterszerzo** [comment]
Both are 240px :)

**Comment by micha-f** [comment]
Oh crap - I had zoomed to 110%... 🥇
