### ISSUE TITLE
Ability to set hard constraints on date range (date picker).

### ISSUE THREAD

**Issue by nagautier** [contiamo/operational-ui#388]
Right now, a user can specify any date range on the calendar. Often some data is only available for a certain date range. Clicking outside the range results in no data, which can be frustrating to the user as they are not always aware of the available data date range.
It would be useful to be able to specify hard limits on the date range above which the user cannot click (greyed out for example).

**Comment by peterszerzo** [comment]
Awesome - great feature suggestion, @nagautier, we'll see if we can squeeze it in this week!

**Comment by TejasQ** [comment]
@peterszerzo what's the status here? @nagautier do you still need this?

**Comment by TejasQ** [comment]
Thanks!

**Comment by peterszerzo** [comment]
I can take care of it by Monday close of business.

**Comment by TejasQ** [comment]
Merged in #594, closing.
