### ISSUE TITLE
Switching months closes date picker menu.

### ISSUE THREAD

**Issue by nagautier** [contiamo/operational-ui#396]
Changing months in the date picker causes the menu to close. The month is actually changed but it's annoying to have to click twice every time :).

**Comment by peterszerzo** [comment]
Thanks for reporting, @nagautier, I'll take care of it!

**Comment by TejasQ** [comment]
Hahaha @nagautier, couldn't find a GIF tool, eh?

**Comment by peterszerzo** [comment]
@TejasQ only you use the GIF tool :)

**Comment by peterszerzo** [comment]
In other words, @nagautier's one word is worth a thousand GIF's 🥇

**Comment by nagautier** [comment]
I did, it crashed my computer. So I went with words instead :)

**Comment by peterszerzo** [comment]
@nagautier this issue should be fixed in the `0.1.0-30` release. Would you mind checking if it works for you, and if so, closing this issue?

**Comment by nagautier** [comment]
Working now!
