### ISSUE TITLE
Buttons and inputs are not the same size

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#407]
Not sure if this is intentional or not, but a button next to an input looks a little wonky (see screenshot). Shall we make them closer to the same size, height-wise? What is the thinking around this topic?

<img width="306" alt="screen shot 2018-04-18 at 17 18 03" src="https://user-images.githubusercontent.com/9947422/38941266-78bf01a4-432c-11e8-8b3e-0f831ca41e5a.png">

**Comment by peterszerzo** [comment]
Yepp, they should be, one of those things that broke with the theme spacing changing :/ I'll take care of it tomorrow.
