### ISSUE TITLE
Marathon minor improvements

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#409]
- Can we show a spinner for the currently executing step (instead of the "...")
- When I click the loop button it jumps over the next test case, then starts
- When I click the pause button it only stops on the next case, not the current one
- Shall we add a label like "run all" to the loop icon?
- Can we open the code in a new window and add an icon that clarifies that that's what will happen?

**Comment by peterszerzo** [comment]
I wonder if the spinner would make the interface misleading, since actually nothing is happening in those 2 seconds.

**Comment by peterszerzo** [comment]
I am remaking the website to use new components, and as soon as I'm done, we can revisit this and see where the elements should go.

**Comment by TejasQ** [comment]
Mind referencing the PR here?

**Comment by peterszerzo** [comment]
Of course :) #520

**Comment by peterszerzo** [comment]
The code generating this issue has moved - the fixes are taken care of partially in https://github.com/contiamo/operational-visualizations/pull/3, and https://github.com/contiamo/operational-visualizations/issues/4 has been opened to cover the rest.
