### ISSUE TITLE
Sunburst case01 seems broken

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#410]
![image](https://user-images.githubusercontent.com/200647/39120925-541e24fc-46f0-11e8-9057-7b34cf18e38e.png)

This happens if one navigates away from the page while the animation is happening and then comes back.

**Comment by peterszerzo** [comment]
@micha-f I can't reproduce this unfortunately. It would be helpful to have the following details:
* your browser version
* whether the looping active at that point
* how long do you wait until navigating away and back

**Comment by micha-f** [comment]
I think this is not related to marathon but the visualization animations

**Comment by peterszerzo** [comment]
Looks like it has to do with what we discussed on defining mutated input data as a top-level module variable, @ImogenF - mashing those over to functions called fresh inside the marathon function should do the trick.

**Comment by ImogenF** [comment]
@peterszerzo I don't think that's the problem in the case. Nicolas came across the same problem. I thought I'd fixed it, may just need to update the data to reflect the fix.

**Comment by ImogenF** [comment]
Sorry, completely forgot about this. Still seems to be a problem here, will look at it today.

**Comment by ImogenF** [comment]
#570

**Comment by ImogenF** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix sunburst when screen not active](https://trello.com/c/6QCxvmjy/262-fix-sunburst-when-screen-not-active)
