### ISSUE TITLE
Separate breadcrumbs and back link from content

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#416]
@peterszerzo  I've been clicking around in Pantheon UI a bit and I find myself using the "back link" quite a bit. It's easy to "hit" (big enough).
That said, I agree it's not "perfect" yet. What do you think about separating the navigational components (breadcrumbs and back link) from the content a bit (see below as one way of doing it)?

![image](https://user-images.githubusercontent.com/200647/39296405-1b1bb4f0-4941-11e8-9ac5-fe2e26cf478f.png)

**Comment by peterszerzo** [comment]
While it does improve separation between nav and content, the clutter it adds - especially when embedded - is not ideal. Take it as openness as opposed to negativity, but I think this is another step in a problematic direction just for the sake of accommodating the back button. I spent hours using it now, and find myself not trusting it (maybe it's there, maybe it isn't), where it leads to is unintuitive (should a back button at the edit page go to details or the list, if I'm hitting the button on a reflex? why don't I just use the breadcrumbs which are predictable?) and adds two links 1.5cm apart that do the same thing.

**Comment by micha-f** [comment]
I think we just have very different opinions on the back button 😆

**Comment by micha-f** [comment]
These are my main points:
- Every time I click on the breadcrumb, I need to think. There are multiple items in the breadcrumb - which one do I need to click on?
- The clickable area of the breadcrumb is smaller = takes more effort and longer to click

I really like the "Don't make me think" approach (https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think) 

"People are good at satisficing, or taking the first available solution to their problem, so design should take advantage of this."

I believe that on most of the "show" pages, going back to the list is the most commonly used action.

**Comment by micha-f** [comment]
@peterszerzo let's take out the back button for now and see how things feel. We need to make sure that the browsers "back" button works absolutely reliable in this case.

**Comment by peterszerzo** [comment]
The browser's back button is very reliable the way the UI is set up currently.

I have one last remark to the don't make me think philosophy: right now, we have 4 buttons in a 5cm x 5cm range in the upper left corner of the screen that do the exact same thing: side nav, breadcrumbs, browser's back button, and the back link we added yesterday. That's a lot of options to choose from, or think about.
