### ISSUE TITLE
<Page> doesn't deal with the height of the header

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#424]
When I have a `<Page />` into the `<OperationalUI />`, the height of the page in not correct. In fact the `<Page />` have `heigth: 100%` without take care to the header height.

### Code

```jsx
<OperationalUI withBaseStyles>
    <Router>
      <Layout
        css={{ height: "100vh" }}
        sidenav={
          <Sidenav expanded>
                <SidenavHeader label="hello" icon="Star" />
          </Sidenav>
        }
        main={
          <div>
            <Header>Identity Provider</Header>
            <Page title="hi">
              my content
            </Page>
          </div>
        }
      />
    </Router>
  </OperationalUI>
```

### Result

![image](https://user-images.githubusercontent.com/1761469/39570616-248dfaba-4ec9-11e8-8b88-2f58d1176e95.png)

(issue on bottom, when we scroll)

**Comment by peterszerzo** [comment]
Thanks for reporting, @fabien0102 - the `Layout` component's `main` prop doesn't take a header anymore. I'll make it clear in the docs and flag you when it's ready :)
