### ISSUE TITLE
Add anchor navigation to website

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#433]
It would be quite nice to have https://operational-ui.js.org/#checkboxes take you straight to _that_ component's demo. 

Thoughts?

**Comment by peterszerzo** [comment]
Absolutely :) components generally support `id` attributes so you can pin one on the card.

**Comment by TejasQ** [comment]
Guess this works already...

**Comment by peterszerzo** [comment]
Nope, the anchor doesn't :) the point would be to have an anchor that you can click on, which would change the hash so you can enter the accurate url into slack for instance to point out a bug in a component.

**Comment by TejasQ** [comment]
But [this does that](https://operational-ui.js.org/#progresss) already...

**Comment by peterszerzo** [comment]
I'd still say we can use some actual anchors that change the hash (probably best on the slow-burner).
