### ISSUE TITLE
withBaseStyles should be assumed

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#456]
After implementing Operational UI in a number of UIs, `withBaseStyles` is being used extensively and seems to be a seemingly unnecessary piece of boilerplate. I propose we use base styles by default, and instead have a `noBaseStyling` prop or similar to allow for customization.

Thoughts?

**Comment by peterszerzo** [comment]
I would say that since conflicts between injected pieces of CSS can be so frustrating to debug, this is good to have around explicitly. It also makes it clear that you're opting into the whole Operational thing, and not just an isolated snippet or a single visualization.

**Comment by TejasQ** [comment]
I hear you. In contrast though, in the beginning, we said (and still adhere to) the idea that it should be an opinionated way to build operational UIs. I would argue that opting into base styles breaks that opinionation.

**Comment by fabien0102** [comment]
As a new member in this project, I'm totally agree with @TejasQ , the basic bootstrap should be with a base style assumed. It's a ui kit. And for customization, normally the `theme` props should do the job, no?

**Comment by peterszerzo** [comment]
Good points, fellas, let's do it! It'll be the first use of the `deprecate` HOC.

**Comment by TejasQ** [comment]
Incredible.

**Comment by peterszerzo** [comment]
Fixed with #553
