### ISSUE TITLE
Card and card header

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#476]
![image](https://user-images.githubusercontent.com/9947422/40925005-ee6a0820-6818-11e8-8dc9-dcebcbb37ea8.png)

To fit the new design, we'll need to update `Card`s to look like the above figure.

### Card Layout with Columns

```jsx
const MyAction = () => <>You can eat sushi like this. <a href="#">Learn more</a></>
// or...
const MyOtherAction = () => <Link to="/heaven"><Button>Hello</Button></Link>

<Card
  title="Bundle Information"
  action={MyAction}
>
  <CardColumn title="Contributors">
   <AvatarGroup collaborators={[]} />
  </CardColumn>
  <CardColumn title="Tags">
    <Chip>agent-view</Chip>
    <Chip>agent-view</Chip>
  </CardColumn>
</Card>
```

### Card Layout _without_ Columns

```jsx
const MyAction = () => <>You can eat sushi like this. <a href="#">Learn more</a></>
// or...
const MyOtherAction = () => <Link to="/heaven"><Button>Hello</Button></Link>

<Card
  title="Bundle Information"
  action={MyAction}
>
  <CardTitle>Contributors</CardTitle>
   <AvatarGroup collaborators={[]} />

  <CardTitle>Members</CardTitle>
   <AvatarGroup members={[]} />
</Card>
```

**Comment by micha-f** [comment]
Shouldn't we separate columns from content headers (you called them CardTitle)?
You could have multiple CardTitles and content in one column.

How about <CardColumn> purely for arranging content?

**Comment by fabien0102** [comment]
@micha-f The `<CardColumn title="Tags"></CardColumn>` is just a shortcut for:

```jsx
<CardColumn>
  <CardTitle>Tags</CardTitle>
  {/* content */}
</CardColumn>
```

The idea is to provide an easy way for simple cases, but of course, if we have more than one title, it make sense to not use this shortcut.

**Comment by micha-f** [comment]
@fabien0102 that's nice!

**Comment by TejasQ** [comment]
What @fabien0102 said.

**Comment by ImogenF** [comment]
Why do the actions need to be functions? Is this a convention I'm not aware of?

Also, I'm assuming we might want to allow some card content to be rendered *outside* of the card columns, right? I'm thinking it makes sense to have a CardColumns container component that groups CardColumn components.

**Comment by micha-f** [comment]
I would say that a function provides more flexibility and can return different values when it's re-evaluated - for example if it closes over some variable which it uses during evaluation.

**Comment by fabien0102** [comment]
It's not really a function in this context (it's a function but not only) it's a `React.ComponentType`.

The idea is to permit to easily extract any sub-component outside and give more flexibility ;)

So with the same example, we can have this kind of implementations:
```tsx
import CardAction from "./CardAction" // this export a props=>JSX.element or a classic React.Component

<Card
  title="Bundle Information"
  action={CardAction}
>
  <CardTitle>Contributors</CardTitle>
   <AvatarGroup collaborators={[]} />

  <CardTitle>Members</CardTitle>
   <AvatarGroup members={[]} />
</Card>
```

And can also give any `CardAction` props inside the `Card` component.

If we do this (with the jsx notation):
```tsx
<Card action={<CardAction />} />
```
You can't give any props to `CardAction` into `Card` 😉

**Comment by TejasQ** [comment]
The idea behind having actions as React components (which _can be called_ functions), is that each component can have its own `onClick` handler to do whatever it wants to. 

Consider,
```jsx
const MyReactComponentAction = () => <div onClick={() => alert('eat KFC!')}>Give me bad advice!</div>

/* later, when using this component, */

<Card
  title="Bundle Information"
  action={MyReactComponentAction}
  {/* could also be written like below */}
  action={() => <MyReactComponentAction />}
>
  <CardTitle>Contributors</CardTitle>
   <AvatarGroup collaborators={[]} />

  <CardTitle>Members</CardTitle>
   <AvatarGroup members={[]} />
</Card>
```

@ImogenF your question is a really good one! _Should_ we call them `actions` when they're components? Seems a little ambiguous because one would expect `actions` to almost be a dictionary of actions. Maybe we can call them something else? Should we? 

About columns, I think you're _absolutely right_. What do you think about this example illustrating a card that has columns _and_ stuff outside the columns?

```jsx
<Card
  title="Bundle Information"
  action={MyAction}
>
  Hello, I live outside the columns and I'm a free man!
  <CardColumns>
    <CardColumn title="Contributors">
     <AvatarGroup collaborators={[]} />
    </CardColumn>
    <CardColumn title="Tags">
      <Chip>agent-view</Chip>
      <Chip>agent-view</Chip>
    </CardColumn>
  </CardColumns>
</Card>
```

@fabien0102 what do you think?

**Comment by TejasQ** [comment]
Great idea about `actionComponents`, @ImogenF! But what about the (I expect common) case that you have just _one_ action component?

**Comment by ImogenF** [comment]
@TejasQ I put this in and then took it out again after a discussion with @fabien0102. 

Summary:
- plural doesn't make sense, since it might not always be plural
- adding a `Components` suffix is inconsistent with how other components are named

So it's staying as `action` until/unless we can figure out something better 😉

**Comment by TejasQ** [comment]
Makes sense. We could even describe it by saying `action` is the name of an area in a CardHeader that is the upper-right side.
