### ISSUE TITLE
<Icon /> should support configurable css via prop

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#488]
Currently, the Icon component is impossible to customize with a style – with a `css` prop. What happens when a user wants to add custom padding or margins?

**Comment by peterszerzo** [comment]
This is intertwined with our verbal discussions on removing `css` attributes from components, for which I just opened an issue: #511.

So far, I have done margin and padding styles by setting child selectors like `& > svg: { margin: 4 }` on the parent (consistent with child styling that doesn't rely on `css`), and for colors, setting the `color` on the parent will propagate through the use of `currentColor`. `size` is already configurable.

**Comment by fabien0102** [comment]
If I'm right, @TejasQ add `right` and `left` props to the `Icon` to deal with kind of spacing usecase ;)

**Comment by TejasQ** [comment]
Fabien was right.
