### ISSUE TITLE
Page - Tabs - Layout components

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#504]
## Goal

Have a nice set of components to deal with the main page structure following the next mockups.

### Simple Page

![image](https://user-images.githubusercontent.com/1761469/41584039-7f504a32-73a6-11e8-8495-337993ed0cec.png)

```tsx
<Page title="Bundles">
   <Layout main>
      <Card title="Bundles" />
   </Layout>
</Page>
```

### With Tabs

![image](https://user-images.githubusercontent.com/1761469/41584050-8d58129a-73a6-11e8-904f-4ab13c091c8c.png)

```tsx
const OverviewPage = () => (
  <>
    <Layout main>
      <Card title="Bundle information" />
      <Card title="Readme" />
    </Layout>
    <Layout side>
      <Card title="Deploy functions" />
      <Card title="Sync meta data and Jobs" />
      <Card title="Repository" />
    </Layout>
  </>
)

<Page
  title="Bundles: Agent View"
  action={() => <Button color="info" icon="ExternalLink">Launch Editor<Button/>}
  tabs=[{ name: "Overview", component: OverviewPage } /* ... */]
 />

```

## Ideas

Ideally, the `Page` component will instanciate for us a sub router, so in the last example, if I am on the `overview` section, the url should reflect finishing with `/overview`. So no need to have an `activeTabs` props, and our product is more accessible.

Note: The first tab is the `index` sub route

**Comment by TejasQ** [comment]
Thanks for the issue! I have some thoughts about this, but for now, here's a screenshot with more use cases for this component.

![image](https://user-images.githubusercontent.com/9947422/41585252-ccbf218c-73a9-11e8-8abc-7e93dc78083d.png)

**Comment by TejasQ** [comment]
Here's a more hands-on proposal: [![Edit n92zzy1x7p](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n92zzy1x7p)
