### ISSUE TITLE
Paginator

### ISSUE THREAD

**Issue by ImogenF** [contiamo/operational-ui#506]
![image](https://user-images.githubusercontent.com/14272822/41592375-a51c7f86-73bc-11e8-8380-97c8fbd955c2.png)

## Proposed API
```jsx
<Paginator
  itemCount={258}
  page={this.state.page}
  itemsPerPage={50} 
  onChange={page => this.handleChange(page)} 
/>
```

The "first"/"prev" and "next"/"last" buttons only show up if the first/last items are not being displayed.

**Comment by TejasQ** [comment]
I believe you have the wrong screenshot...

**Comment by ImogenF** [comment]
https://trello.com/c/Fku5UWiB/191-pagination-component

**Comment by TejasQ** [comment]
Great API! I think conditionally rendered buttons based on props could be nice: only show a next button if given an `onNext` prop and so on.

**Comment by ImogenF** [comment]
@TejasQ You mean replace `onChange` with `onNext`, `onFirst`, `onPrev` and `onLast`? That would be nice, but I think the user shouldn't have to determine whether page 5 is the last page or not and only pass an `onLast` prop accordingly. How about only showing a next button if an `onNext` prop is provided *AND* if `props.itemCount` < `props.page` * `props.itemsPerPage` ?

**Comment by ImogenF** [comment]
#507

**Comment by ImogenF** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pagination component](https://trello.com/c/Fku5UWiB/191-pagination-component)

**Comment by fabien0102** [comment]
Regarding the `onChange` vs `onNext/onPrev`, I also think that the `onNext` can be interesting, maybe keep the both options for now (it's really depends how we deal the pagination with the backend, so both options can be nice here)

But yes, what even we choose, we need to disable button regarding the state (disable first if we are of first page, etc) :wink:

**Comment by ImogenF** [comment]
@fabien0102 The disabling is in there already.

I really think `onNext/onPrev` would overcomplicate things and I'm not sure I see any benefit to it - in all cases, we just want to change `state.page`, so either we keep the logic in the `Paginator` component, as it is now, or we move it out into the `onNext` etc methods and trust the user to set it up correctly.

**Comment by TejasQ** [comment]
Merged.
