### ISSUE TITLE
Add `className` prop to all components

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#517]
~~Relying on class names is brittle, risking typos (or making string constants necessary) and opening up an escape hatch to meddle with the insides of components. It is better to remove `className` props entirely and rely on `emotion` component-based styling instead.~~

After running into some tricky-to-debug styling errors using the components, the scope of this PR has changed. Read along :)

**Comment by peterszerzo** [comment]
I ran into the following classname-related issue: not passing `className` prop to a component makes it impossible to use `emotion`'s `styled` helper, an escape hatch that is necessary in internal implementation (e.g. `Icon.tsx`), as well as in hotfixes on client code. Worse yet, the error goes silent, and proved to be very difficult to debug. In light of this, I recommend we always pass class names to all our components.

Quick context here: in the `css` prop removal discussion, it came up that using `styled` is a more verbose than writing `<Button css={{ marginRight: 0 }} />`, and therefore should discourage itself as a CSS override escape hatch by virtue of being annoying to write.

**Comment by TejasQ** [comment]
I'm totally in favor of allowing a `className` prop everywhere. I think it makes sense for components to receive `className`s all the time, but _not_ ad-hoc `css` styles.

Good catch, Peter!

**Comment by fabien0102** [comment]
I think that we can try this pattern for our module -> https://github.com/pedronauck/docz/blob/master/examples/typescript/src/components/Alert.tsx

So we retrieve all native react props (including classname), and it's pretty 😎

**Comment by TejasQ** [comment]
How about we just spread props in `Container`s?

**Comment by peterszerzo** [comment]
That's what @fabien0102's link suggested as well I believe
