### ISSUE TITLE
Type definitions paths are incorrect

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#527]
When installing `@operational/components` into a new project, the typings files contain incorrect import paths when requiring dependant interfaces, missing an additional `../`. This causes typescript compilation to fail on projects depending on this package.

E.g. `node_modules/@operational/components/lib/Icon/Icon.d.ts` will contain this line:

```ts
declare const _default: import("../../../../node_modules/create-emotion-styled/types/react.d.ts").StyledOtherComponent<{}, import("../../../../node_modules/emotion-theming/types/index.d.ts").OptionalThemeProps<PropsWithTheme, {}>, any>;
```

Imports should instead start with `../../../../../node_modules`.

Looks like the error crept in after introducing the new build + babel plugin, though I do not have a clear idea on what exactly about it caused the issue.

**Comment by peterszerzo** [comment]
@contiamo/frontend if anyone runs into compile issues, adding the following hack as a postinstall node script will get things running at least (adapt depending on where your script is located):
```
const fs = require("fs")
const path = require("path")

const typingsBasePath = "../node_modules/@operational/components/lib"

const replace = typingsPath => {
  const typingsAbsolutePath = path.join(__dirname, typingsBasePath, typingsPath)
  const typingsContents = fs.readFileSync(typingsAbsolutePath, "utf-8")
  const hackedTypingsContents = typingsContents
    .replace(/\.\.\/\.\.\/\.\.\/\.\.\/node\_modules\//g, "")
    .replace(/\.d\.ts/g, "")
  fs.writeFileSync(typingsAbsolutePath, hackedTypingsContents)
}

replace("Icon/Icon.d.ts")
replace("Typography/Typography.d.ts")
replace("Tabs/Tabs.d.ts")
```

**Comment by peterszerzo** [comment]
@TejasQ unfortunately https://github.com/contiamo/operational-ui/pull/567 doesn't fix this. Steps to reproduce:
* run yarn package on the latest master.
* navigate to `packages/components/lib/Tabs/Tabs.d.ts`, where the file will look like this:

```
import * as React from "react";
import { OperationalStyleConstants } from "../utils/constants";
export interface Props {
    className?: string;
    id?: string;
    /** Index of the active tab. */
    active?: number;
    /** Active color. It can be a hex value or a named theme color. */
    activeColor?: string;
    children?: React.ReactNode;
    /** Function to be called once the tab index changes. */
    onChange?: (index: number) => void;
}
export interface PropsWithTheme extends Props {
    theme?: OperationalStyleConstants;
}
declare const _default: React.ComponentClass<import("../../../../node_modules/emotion-theming/types/index").OptionalThemeProps<PropsWithTheme, {}>>;
export default _default;
```

Unfortunately, the 4x `../` instead of 5x is still there.

**Comment by TejasQ** [comment]
Will look into it. Thanks, @peterszerzo.

**Comment by TejasQ** [comment]
@peterszerzo, I'm having a hard time reproducing this.

Here's a screenshot after `yarn package` from the latest master on `packages/components/lib/Tabs/Tabs.d.ts`.

![image](https://user-images.githubusercontent.com/9947422/42436735-4bea9c1e-835b-11e8-89d3-6faa71fb576c.png)

**Comment by peterszerzo** [comment]
I was working off the latest master, but I'll replicate on a different machine tomorrow and see if it persists. This looks very promising, though!

**Comment by peterszerzo** [comment]
@TejasQ the issue persists, I'm getting the same `.d.ts` file as I copied in earlier.

**Comment by peterszerzo** [comment]
Not exactly I'm afraid - the hoisted dependency issue still persists. It'll go away as soon as components move to their own file. Until then, postinstall hacks do the job :)

**Comment by TejasQ** [comment]
You're right. I'm looking forward to the factoring out of components.
