### ISSUE TITLE
Project selector and user menu

### ISSUE THREAD

**Issue by ImogenF** [contiamo/operational-ui#561]
## Project Selector and User Menu
Project selector: https://trello.com/c/hMNW8dop
User menu: https://trello.com/c/VSs4XyMC

There are two possible APIs.

### Proposed API 1
The first option is to make 2 simple components, a `ProjectSelector` and a `UserMenu` (naming open for discussion). These are just  the clickable parts of the header bar, which trigger context menus. This has the advantage of allowing each option in the menus to have its own `onClick` method, since, unlike in a `Select` dropdown component, the actions might be completely different. For example, one might open a pop-up, another might navigate to a new screen, etc. Since this is only really necessary for the user menu, we could enable an `onClick` prop within the `ContextMenu` as a shortcut which passes the same method on to all `ContextMenuItem`s.

```
<ContextMenu>
  <ProjectSelector>Click here</ProjectSelector>
  <ContextMenuItem onClick={() => alert("clicked")}>Menu 1</ContextMenuItem>
  <ContextMenuItem onClick={() => alert("clicked")}>Menu 2</ContextMenuItem>
  <ContextMenuItem onClick={() => alert("clicked")}>Menu 3</ContextMenuItem>
</ContextMenu>
```

 OR:

```
<ContextMenu onClick={() => alert(“clicked”)}>
  <HeaderMenu>Click here</HeaderMenu>
  <ContextMenuItem>Menu 1</ContextMenuItem>
  <ContextMenuItem>Menu 2</ContextMenuItem>
  <ContextMenuItem>Menu 3</ContextMenuItem>
</ContextMenu>
```

### Proposed API 2
The other alternative is to create 2 more complex components which use `ContextMenu` internally. This would simplify things for the end user.
```
const projectOptions = [
  { key: “project1”, label: “Project 1” },
  { key: “project2”, label: “Project 2” },
  { key: “project3”, label: “Project 3” },
]
<ProjectSelector options={projectOptions} active={this.state.activeProject}></ProjectSelector>

const userOptions = [
  { label: “My account”, onClick: () => {…} },
  { label: “Logout”, onClick: () => {…} },
]
<UserMenu options={userOptions}></UserMenu>
```

**Comment by peterszerzo** [comment]
My initial feeling goes towards option 1. It doesn't look like too much trouble to write out the context menu explicitly, and it would allow the project selector and user menu components to be more presentational and re-usable. Also saves the trouble of converting data available in the parent component be converted into the `projectOptions` structure, and handle the data that comes back from the components (since most likely they'll have to be controlled). Instead, you'd just memorize how context menu works and recognize it everywhere.

**Comment by ImogenF** [comment]
@peterszerzo My only concern about writing out the context menu explicitly is that if the menus are going to be reused in a lot of places, but with identical functionality, it seems like a lot of code duplication and therefore more scope for error. Whereas with the 2nd option, we could configure it so that the list of projects received from the backend can be passed directly into the `ProjectSelector` component as they are. And for the `UserMenu` we could simply pass the user data in, since the menu options will presumably always be same.

**Comment by TejasQ** [comment]
🤔 

I'd prefer a middle way between both options. Consider,

```jsx
<Dropdown items={[{ label: "Thing", onClick: () => {} }]}>
  Tejas Kumar <Avatar />
</Dropdown>
```

The stuff inside `Dropdown` would then highlight if it is extended or hovered or in some other state. When `Dropdown` is clicked, it exposes its `items` and handles clicks on them accordingly. 

You might even need a higher-level `onChange` handler as a prop on `Dropdown` if each item ends up having the same `onClick` handler.

**Comment by ImogenF** [comment]
That's basically option 2, but with a single component rather than 2 separate ones, right? So the `Dropdown` component uses `ContextMenu` internally and can either apply `props.onClick` to all, or `item.onClick` to each item. 

My only reason for keeping them as 2 separate components was that the styling is a bit different - same hover behaviour and everything, but different layouts. But I'm sure that can be generalised somehow.

**Comment by ImogenF** [comment]
Also, given that these would only be used inside a header, I think it would be better to call it `HeaderMenu` or `HeaderDropdown`, for clarity.

**Comment by ImogenF** [comment]
Even if we have a footer menu in the future, that would need to behave a bit differently, wouldn't it? Context menu would have to expand upwards, etc. And the styling might be different too. Not sure it's worth worrying about that too much right now.

So I'll go ahead and work on this for now, if anyone objects or has any other improvements to suggest please let me know!

**Comment by ImogenF** [comment]
#566

**Comment by TejasQ** [comment]
Merged, closing.
