### ISSUE TITLE
Tree component

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#590]
This is an API proposal for the tree component per the following sketch:

![image](https://user-images.githubusercontent.com/6738398/42750307-16a1215e-88e7-11e8-9aaf-06d02e1da649.png)

### Design goals

* component renders elements in a folder tree-like structure, rendering a label and an optional `NameTag` at each node. The component should be agnostic about the level of nesting to avoid verbose type definitions.
* supports any HTML attributes and event listeners at each level - both click events as well as drag-and-drop handlers are important for individual nodes.
* the outside world need not know about open-closed state - this should be handled in internal state.
* opinionated on node styling (font-weight, color etc.) based on the nesting level / whether there is a tag or not.

### API

The basis for the props of this component is a recursive data structure that models an arbitrarily nested tree:

```
export interface Tree {
  label: string
  tag?: string
  childNodes: Tree[]
}
```

Create a component like so:

```
(
  <Tree
    tree={{
      label: "Dimensions",
      childNodes: [
        {
          label: "Dim 1",
          tag: "DM",
          childNodes: [],
        },
        {
          label: "Dim 2",
          tag: "DM",
          onClick: () => {
            console.log("clicked")
          },
          childNodes: [
            {
              label: "Subdim 1",
              tag: "SM",
              childNodes: [],
            },
          ],
        },
      ],
    }}
  />
)
```

The component's implementation handles active state by keeping track of active node paths in an array, sorting out conflicts when new props arrive (although this should be infrequent).

**Comment by ImogenF** [comment]
Since it is possible to add custom `onClick` events to any node, regardless of its level in the tree, how would that influence expanding / collapsing parts of the tree? Is expanding/collapsing done by clicking on the arrows or plus signs, and `onClick` is assigned to the NameTags and text only?

Also, will there be a shortcut to add the same event listener to each node, or to each node that has no children of its own, which takes `node` as an argument? e.g. 
```<Tree onClick={(node) => { !node.childNodes.length && console.log(node.label) }} tree = {{...}}/>```

**Comment by peterszerzo** [comment]
We can do a few things on `onClick` combined with internal `onClick`: call both at the same time, have one work on arrow/chevron click and the other on label click, or allow the user to customize. I think it's best to decide after a first pass of the implementation.

I don't see the benefit of adding a shortcut or extra sugar for passing node event handlers - if anything, it will encourage the kind of equality checks that you sketched out which I would argue can turn brittle in certain use-cases. I reckon you can achieve the same programming style using something like this:

```
const onNodeClick = node => node.label === "SpecialLabel" ? () => {} else undefined

<Tree tree={{
  label: "",
  childNodes: nodesFromBackend.map(node => ({
    ...node,
    onNodeClick: onNodeClick(node)
  }))
} />
```

This way, it is the client's responsibility to have the wiring working correctly, and looks awkward enough to encourage a refactor.

**Comment by TejasQ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Simple expandable tree with 3 levels](https://trello.com/c/hAECaWyR/178-simple-expandable-tree-with-3-levels)
