### ISSUE TITLE
PageContents cannot be stacked

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#599]
In order to support the case below, we need two `PageContent`s:
![image](https://user-images.githubusercontent.com/9947422/42816736-1747db26-89cc-11e8-94b4-a113909cc607.png)

Would require JSX along the lines of 

```jsx
<PageContent areas="main side">
    <Card title={`Job: ${data.name}`}>hi</Card>
    <Card title="Job Executions">I am not gay</Card>
  </PageContent>
<PageContent>
  <Card title="Bundle Events">Hi</Card>
</PageContent>
```

Except currently, `PageContent` assumes it will be the _only_ `PageContent` and takes the entire height of its container, rendering the second `PageContent` below the fold, under the page, out of immediate sight.

**Reproduction**
![image](https://user-images.githubusercontent.com/9947422/42816997-fa2d23a6-89cc-11e8-8813-d65d8211cba4.png)

How can we solve this? @fabien0102 @peterszerzo

**Comment by fabien0102** [comment]
For me we should keep only one `PageContent` (semantically is good) but improve our API to permit this kind of thing.

Proposition:
```jsx
<PageContent>
  <PageAreas areas="main side"><Card /><Card /></PageAreas>
  <PageArea><Card /></PageArea>
<PageContent>

**Comment by peterszerzo** [comment]
Extending the functionality doesn't come for free on the implementation level. All that these layouts have in common is that they extend to a certain height of their container and lay out their contents in a specific configuration, which I would argue is too little common ground to justify putting everything into a single component. A single grid-positioned parent with its own unique template column setting does the job done, and keeps the implementation readable.

**Comment by TejasQ** [comment]
I think the having one component per layout would make our users (in this case, me as a user) have to keep track of far too many moving parts.

Ultimately, I tried to do something the way I _naturally expected it to work_, and then a bug bit me. A bug with height `100%`. 

I think adherence to an API close to what I tried to do before I got bit makes the most sense, as it would be closer to what developers would normally expect; unless I develop with strange, unexpected patterns all the time.

**Comment by peterszerzo** [comment]
What I'm suggesting also deals away with `PageContent` vs. `PageArea`-type dilemmas, flattening down the card structure entirely, or at least putting them into different molds. That way, you can just go to a shelf and pick between a few well-named layout components. Want the layout with many cards on the left and a big one on the right? Just use `<ManyLeft lefts={[]} main={<Card />} />`. Need a simple page? `<SimplePage><Card /></SimplePage>`. Any requirement that comes in in the future can just get its own layout component and not bloat the structure, or impose some special stacking behavior on contents and areas that may work for us for a new use-case or may not.

I think that making a decision that is largely informed by a public API that looks nice to read can lead to trouble down the line. I'm not the one who would usually say this, but I would argue that layout is a different beast to wrestle.

**Comment by fabien0102** [comment]
For the confusion between `PageContent` and `PageArea` I think that we can just improve the documentation. We only need `PageContent` with tabs case to have a semantic container, otherwise everything is deal for you and you just need to have some `PageArea` to separate your page in area. Until here, the API seams not to bad for me.

I also suggest to add a development warning if we have multiples `PageContent` into `Page` to avoid this kind of confusion.

**Comment by peterszerzo** [comment]
I agree that these are useful additions, but at the same time, having to do runtime warnings are a sign that the design will difficult to take in and maintain by a new developer, or even one seasoned with this codebase. This project has evolved in a manner that prefers compile-time safety and strict API's, and the `PageContent - PageArea` direction is shaping up to go against it.

**Comment by fabien0102** [comment]
I will love to have a compile-time error for this, and I will try to implement this kind of type safety for sure. 

But I'm not really agree with your argument about runtime warnings and new developers. React for example, have a lot of runtime warnings, same for redux and many other libraries. Sometime it's just easier to add a runtime warning :wink:

Idea for the compile-time safety: https://codesandbox.io/s/3v6pmjzj8p

**Comment by peterszerzo** [comment]
I didn't mean that runtime warnings are a bad thing, I mean that when you rely on them to enforce the idiomatic use of an API, it can indicate that the API's design can use improvement, or that a different API might make them unnecessary. In this case, I think we should strive for that.

The same holds for the implementation idea in the sandbox - I certainly agree that it is clever, but I think it merely patches up the design's drawbacks.

**Comment by TejasQ** [comment]
The above PR will require minimal changes to my existing implementation in the Labs UI and I think it is more idiomatic. Let's use it.
