### ISSUE TITLE
[Optimisation] Scoping event listener of `Select`

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#605]
https://github.com/contiamo/operational-ui/blob/9b829c408d6ae09322fc40dfaac960295ab761f9/packages/components/src/Select/Select.tsx#L179:14

This component should listener the click/esc only if the select menu is open 😉

**Comment by peterszerzo** [comment]
Awesome - are you up for implementing this?

**Comment by fabien0102** [comment]
@TejasQ is on it ;)

**Comment by TejasQ** [comment]
Fixed in #609
