### ISSUE TITLE
Action menu styling

### ISSUE THREAD

**Issue by ImogenF** [contiamo/operational-ui#608]
### Problem

Currently, since `ActionMenu` makes use of the `ContextMenu` component, the two are styled independently. This results in the boxShadow along the top border of the `ContextMenu` overlapping the "Actions" button:

![image](https://user-images.githubusercontent.com/14272822/42933397-f72d6160-8b44-11e8-9123-060cb71aa1a8.png)

Ideally, we would want the box shadow to go fully around the button *and* the menu together.

### Proposed solutions

1) Redesign `ContextMenu`:

Enclosing (a copy of) the item from which the context menu is triggered and the menu itself inside a container, so that the boxShadow can be applied to this container instead of just the menu. This would also be useful for the `HeaderMenu` component as well.

However, this would make `ContextMenu` unsuitable for use with anything except buttons or rectangular divs of the same width as the menu. We don't currently have any uses where this is not the case, but could be problematic. 

2) Do not use `ContextMenu`:

This would require completely redesigning the `ActionMenu` and implementing the menu and its behaviour from scratch.

**Comment by peterszerzo** [comment]
It seems like option 2 is in order, lest we braced ourselves for some unusual implementations or styling hacks. We can pull out parts of the context menu that can be used (the styling of the popup menu itself), add that to the `Internals` folder, and have both context menu and action menu share that. The popup shadow can go either into `utils/mixins` or into the theme, if it isn't there already. There might be some code duplication in the wiring, but I think that's a lesser evil.

**Comment by ImogenF** [comment]
Actually, I may have found a nice solution. In a nutshell:

- Add a flag to `ContextMenu` for including the clickable element within the menu styling. 
- If this flag is `true`, the clickable element (props.children) is simply added as the first menu item, and the positioning of the menu is updated accordingly.

This means that the standard `ContextMenu` is not altered in any way. The `ActionMenu` and any other components that make use of `ContextMenu` can then set this flag to `true` if required, but are then responsible for ensuring that their own styling does not conflict in any way with that of the `ContextMenu`. 

It's working for `ActionMenu` so far: 
![image](https://user-images.githubusercontent.com/14272822/42936380-335e5e62-8b4c-11e8-8e8e-ff2a6de6ba46.png)

The `HeaderMenu` component would need a bit of restyling if we want shadows on that, but shouldn't be too big a deal.

**Comment by peterszerzo** [comment]
That sounds really promising, @ImogenF - probably best to have a flag verbose enough to make sure whoever is using it know what they're doing. Curious to see how it works on the implementation level.

**Comment by ImogenF** [comment]
@peterszerzo Have pushed what I came up with. May need to find a better name for the flag but it's working nicely, at least. Interested to hear what you think.
