### ISSUE TITLE
Hide `Message`

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#630]
`Message` is an internal component. It should be moved from its current location `src/Message`, into `src/Internals`.

**Comment by Jason-JSProject** [comment]
Hi, so how do I move the file from location A to location B?

**Comment by Jason-JSProject** [comment]
Definitely! Same here.  Ok, I cloned it and tried moving the src folder but it looks like I can't move it to folder.  It says Access restricted.

**Comment by TejasQ** [comment]
Don't move the `src` folder! You'll want to move `Message` in `src` to `src/Internals`!

**Comment by TejasQ** [comment]
Here's a quick GIF of what this looks like. Once that's done, run a `yarn install` and then `yarn start` command to see if you have any errors.

![a](https://user-images.githubusercontent.com/9947422/43889375-4a0bd9cc-9bc4-11e8-943d-4e3f661424b9.gif)

**Comment by TejasQ** [comment]
No. 🤔 Are you able to cut and paste?

**Comment by Jason-JSProject** [comment]
It's showing an option to copy but not cut and paste apparently.

**Comment by TejasQ** [comment]
Perhaps try [setting correct permissions on your folder](https://www.linuxquestions.org/questions/linux-newbie-8/how-to-set-folder-permissions-to-allow-777-for-all-files-499739/). Let me know if that helps.

**Comment by Jason-JSProject** [comment]
So if I understand right, I'll need to use the command line on my Chromebook to set the correct permissions?

**Comment by TejasQ** [comment]
Yes. That's the way I'm most familiar with. I'm not sure what distribution of linux you're running (if you're running linux on your chromebook), so this is the most surefire way for to instruct you since I can't predict the UI.

**Comment by Jason-JSProject** [comment]
Ok I had to research how to install linux on chromebook and have it installed now.  Working on getting the files on there.

**Comment by TejasQ** [comment]
You don't really need linux. 😂 I just guessed that that's the OS you had. What Operating System did/do you have?

**Comment by TejasQ** [comment]
Isn't that Linux based? I've been an Apple user for a while so I'm a little out of touch with it. Let me know when things are moved.

**Comment by Jason-JSProject** [comment]
From what I saw, yeah. Ah gotcha. Will do.

**Comment by fabien0102** [comment]
I don't really know what you can or can't do with chrome os, but you can try cloud9 or something similar if you don't have any integrated terminal 😉 

It's a web environment to have all your need to develop, regardless your local configuration 😉

**Comment by TejasQ** [comment]
@Jason-JSProject – strange. Can you post a screenshot or GIF or something to help us understand what's not working?

**Comment by Jason-JSProject** [comment]
I couldn't figure out how to open or move the cloned git repository while in the chrome os and getting them into the linux installation.  The screen I got was:

![image](https://user-images.githubusercontent.com/40498925/44083884-cf5c4706-9f7a-11e8-8dcd-705c7cc35a3d.png)

My installation was missing most of the icons in the picture.

**Comment by sdabhi23** [comment]
@TejasQ may I take this up?

**Comment by TejasQ** [comment]
Yes, @sdabhi23. 

@Jason-JSProject, I'm sorry but I'm going to have to give this to @sdabhi23. I would recommend reading up on computers a bit more before attempting to contribute to projects on GitHub.

My email address is tejas@tejas.qa if you'd like some personal help/mentoring.

**Comment by Jason-JSProject** [comment]
Thanks, @TejasQ. I appreciate it.

**Comment by sdabhi23** [comment]
Hey @TejasQ, should I just move the message component to internals, or should I also move the tests and readme for it too?

I am asking this because in the internals directory none of the components have their own tests or readme files.

**Comment by TejasQ** [comment]
Move _all the things_.
