### ISSUE TITLE
Export Prop typedefs per component

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#642]
Made this to reference in a @todo in one of our projects. Feel free to add more info if you're a maintainer/already know the problem. (@peterszerzo @fabien0102)

**Comment by peterszerzo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Export component prop interfaces](https://trello.com/c/sADD0JeC/344-export-component-prop-interfaces)
