### ISSUE TITLE
`Splash` component improvements

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#650]
This issue describes changes planned for the [Splash](https://github.com/Contiamo/operational-ui/blob/master/src/Splash/Splash.tsx) component in order to make it more customizable.

### Customizable logos

Currently, the `Splash` component's logo is hard-coded `Operational` one, with the spinning animation relying on a state flag set every 8 seconds. This should be customizable for outside projects and other use-cases. The following steps are required to make this happen:
* the `rotation` handling and state management should move from `Splash.tsx` to [`Splash.Logo.tsx`](https://github.com/Contiamo/operational-ui/blob/master/src/Splash/Splash.Logo.tsx). This will allow the spinning logo to be self-contained and swappable to a different one with its own animations.
* `Splash.tsx` should take a `logo?: React.ReactNode` prop to allow for customizable logos. It should default to the current hard-coded one in case one isn't provided.

### Readable colors

Text colors in the `Splash` component are currently hard-coded to white, which won't be readable if the background is set to a very bright color. As in the [`Button` implementation](https://github.com/Contiamo/operational-ui/blob/master/src/Button/Button.tsx#L47) in , this color should toggle between white and dark using the `readableTextColor` utility. This would involve tweaking animation colors, logo colors and backdrop colors.

### Dev workflow

Simply clone the repo and run `yarn install` + `yarn start` to get the dev environment going. See [React Styleguidist](https://github.com/styleguidist/react-styleguidist) for help developing with styleguidist if you haven't had the chance to work with it yet.

**Comment by adeelibr** [comment]
Is this issue done? I see there is a PR already closed referenced to this. @TejasQ :)

**Comment by TejasQ** [comment]
https://github.com/contiamo/operational-ui/pull/647#issuecomment-409495785

It's not done. The closed PR was by a contributor who seemed to have lost interest in implementing this feature. You're more than welcome to come play here!

**Comment by adeelibr** [comment]
Awesome :) So just to sum up again as @peterszerzo said.

- Move rotation logic to `Splash.Logo.tsx` component
- Allow for `logo` prop which is optional, If not provided revert back to the hard coded logo
- Ability to change text color by passing in a prop that would allow to change `animation colors`, `logo colors` and `backdrop colors`

Did I miss anything? :)

**Comment by peterszerzo** [comment]
Hi @adeelibr that sounds about right. What would be nice to see is whether we can reduce the number of color props to one, or two in the worst case. For instance, if the backdrop color is e.g. blue, the logo and text will be white and the animated boxes white with a faint opacity (use the hard-coded implementation as reference). If, on the other hand, it's white, then text flips to black, overlay to black with the same low opacity figure, and same for the animated boxes.

**Comment by peterszerzo** [comment]
`readableTextColor` is a utility we can use to do these kind of calculations, see e.g. the `Button` component for reference.

**Comment by adeelibr** [comment]
I haven't yet seen the entire implementation for `Splash`, i'll have a look at it when I get free from office today and come up with a approach that we can use for this, i'll keep the above mentioned guidelines in mind when thinking for an approach for this. @peterszerzo

**Comment by TejasQ** [comment]
Looking forward to your PR, @adeelibr!
