### ISSUE TITLE
Card header improvements

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#672]
The following design needs are popping up for the `Card` component:
* multiple headers in a single card acting as full-width separators.
* condensed mode.

<img width="232" alt="screen shot 2018-08-14 at 11 34 17 am" src="https://user-images.githubusercontent.com/6738398/44084063-0768d908-9fb6-11e8-9652-1666a50f8d73.png">

Currently, the following `<Card><CardHeader/><SomethingElse/><CardHeader/></Card>` markup turns out something like this:

<img width="236" alt="screen shot 2018-08-14 at 11 33 53 am" src="https://user-images.githubusercontent.com/6738398/44084068-0a379b74-9fb6-11e8-943f-0494176e4816.png">

### API/implementation ideas

The condensed mode can simply mimic the `Button` api:

```
<Card condensed />
```

For intermediate `CardHeader` elements, it is safe to apply top margins differently when the `&:first-child` selector matches as opposed to when it doesn't. In the former case, negative margin should be applied to counter the padding (as it is implemented currently), and in the latter case, positive margin should apply to add some space between the sections that the intermediate headers delienate.

**Comment by TejasQ** [comment]
My question is: are the `CardHeader`s condensed? Or are the `Card`s condensed?

**Comment by micha-f** [comment]
Listing the new UI elements here so we can decide how we cover these: 

"Card sections" within one card - horizontally and vertically
![image](https://user-images.githubusercontent.com/200647/44092465-cddabb14-9fd0-11e8-8179-cf985f79c069.png)
![image](https://user-images.githubusercontent.com/200647/44092489-e14a84b8-9fd0-11e8-9caf-e65999dd8cca.png)

Card disabled overlay
![image](https://user-images.githubusercontent.com/200647/44092521-f87cfa44-9fd0-11e8-8306-a73798466a3a.png)

Drag target area
![image](https://user-images.githubusercontent.com/200647/44092542-0a0205fc-9fd1-11e8-9253-9b45ff50b1eb.png)

"Card section" actions
![image](https://user-images.githubusercontent.com/200647/44092576-1bba66a4-9fd1-11e8-816d-0ada17e5f2de.png)

Card header tabs
![image](https://user-images.githubusercontent.com/200647/44092588-2926808e-9fd1-11e8-8831-415337e5d11e.png)

**Comment by peterszerzo** [comment]
Just to sum up this discussion: instead of modifying the `CardHeader`, we'd be introducing a `CardSection` component that would nested inside a `Card`, will have its own header and content area, and support features like acting as a drop target, being disabled and being stacked horizontally along with its other `CardSection` siblings.

**Comment by TejasQ** [comment]
Yes. Do you have an API idea?

**Comment by micha-f** [comment]
Moved card header tabs to a separate issue as the agreement seems to be that we'll use `CardSection`s here (and not modify the `CardHeader`) -> https://github.com/contiamo/operational-ui/issues/673

**Comment by peterszerzo** [comment]
I would use this as a starting point:
```
<Card stackHorizontal>
  <CardSection title="Title one" dropTarget />
  <CardSection title="Title two" actions={[]} disabled />
</Card>
```

**Comment by micha-f** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Card sections](https://trello.com/c/NoR7L2pS/376-card-sections)

**Comment by peterszerzo** [comment]
@micha-f yes, that's what the `stackHorizontal` prop on the card is supposed to accomplish.
