### ISSUE TITLE
Bug: Paginator is missaligned

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#697]
![image](https://user-images.githubusercontent.com/1761469/44537524-5784ea80-a6ff-11e8-965b-c76b17a5269e.png)

**Comment by nick-barth** [comment]
This would appear to be a perfect use-case for flexbox.  It also appears you have already fixed it, judging from

**Comment by nick-barth** [comment]
It appears there is a conditional here that should be removed, while I am unfamiliar with the syntax, and unsure of the history/context behind `role="button",`, I'd still wager that we should be putting flex on the container every time.

https://github.com/contiamo/operational-ui/blob/f59c010633c3503c77787838fa6271756e4f3ace/src/Paginator/Paginator.tsx#L86-L90

**Comment by fabien0102** [comment]
I think that we can totally refactor this component, I also don't have the history of this `[role=button]` but it's totally overkill for this case ^^ (and also not anymore working…).

**Comment by peterszerzo** [comment]
This issue is ok to close, right @fabien0102?
