### ISSUE TITLE
Confirm modal style is broken

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#698]
### Expected
https://deploy-preview-628--operational-ui.netlify.com/#Layout
![image](https://user-images.githubusercontent.com/1761469/44580365-f9591580-a799-11e8-8ea9-271e08ffe98b.png)

### Actual
https://deploy-preview-695--operational-ui.netlify.com/#Layout
![image](https://user-images.githubusercontent.com/1761469/44580381-08d85e80-a79a-11e8-92c5-6b93824b14ef.png)

**Comment by ericadamski** [comment]
Are those netlify links associated with specific git commits?

**Comment by ericadamski** [comment]
In the most recent code these rules are missing to make the buttons align to the bottom.

```css
position: absolute;
text-align: right;
bottom: 20px;
right: 20px;
```
