### ISSUE TITLE
Allow conditional rendering inside `SidenavHeader`

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#703]
### Summary

Actually this pattern is not possible:

```jsx
<Sidenav compact>
  <SidenavHeader label="Conditional render">
     <SidenavItem label="classic item" />
     {isDev && <SidenavItem label="not possible yet" />}
  </SidenavHeader>
</Sidenav>
```

When `isDev === false`:

![image](https://user-images.githubusercontent.com/1761469/44780750-f471d880-ab82-11e8-966d-740a56bd7140.png)

**Comment by ericadamski** [comment]
This might be an overly simplistic solution, not sure of the amount of use cases that may cause this rendering issue.

If we just add an existence check to this loop here:

https://github.com/contiamo/operational-ui/blob/b6b690da21ec2b8f7be2ca0f757f4fcc3e5ac142/src/SidenavHeader/SidenavHeader.tsx#L196-L199

Wouldn't that solve this rendering problem?

**Comment by nick-barth** [comment]
I concur, while without proper context, it's hard for us to say this is the definitive answer, but from what we currently know, a null check in [SidenavHeader](https://github.com/contiamo/operational-ui/blob/b6b690da21ec2b8f7be2ca0f757f4fcc3e5ac142/src/SidenavHeader/SidenavHeader.tsx#L196-L199) would allow us to conditionally render using `&&`.

**Comment by fabien0102** [comment]
This should probably works ^^ It's actually not a big or complex issue :wink: I was just totally inside a rush when I wrote this issue, so it's more to avoid to forget :wink:

**Comment by fabien0102** [comment]
This is not fixed, shame on me, I'm such a bad reviewer…

**Comment by TejasQ** [comment]
No shame, only encouragement. Fix it. 😛

**Comment by fabien0102** [comment]
First I'm fixing the client demo ^^ After this 😉
