### ISSUE TITLE
Expandable <Code syntax="json" />

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#709]
## Context

![image](https://user-images.githubusercontent.com/1761469/44775717-9dfe9d00-ab76-11e8-8c2e-59b261562cd4.png)

We want to provide nice UX interacting with JSON.

## Actual API

```jsx
<Code syntax="json" >{JSON.stringify(myObject, null, 2)}<Code/>
```

## Proposal
```jsx
<Code syntax="json" src={myObject} />
```

```ts
interface DefaultCodeProps {
   /** Language for syntax highlighting */
  syntax?: string;
  children?: string | string[];
}

interface JSONCodeProps {
  syntax: "json";
  children?: never;
  src: ReactJsonViewProps["src"];
  collapsed?: ReactJsonViewProps["collapsed"];
  shouldCollapse?: ReactJsonViewProps["shouldCollapse"];
}

type CodeProps = DefaultCodeProps | JSONCodeProps
```

All others values from `react-json-view` will be internally define by operational-ui

## Resources
https://www.npmjs.com/package/react-json-view

**Comment by TejasQ** [comment]
I really like this, although I would prefer using `children` instead of putting the code in an `src` prop because it seems a little more idiomatic per the React methodology.

**Comment by fabien0102** [comment]
@TejasQ The actual implementation of `react-json-view` is with `src`, also do you really prefer:

```jsx
<Code syntax="json">{myObject}</Code>
// vs
<Code syntax="json" src={myObject} />
```

I think that for an object, it's more conveniant to use a basic props, to give strings/ReactNodes, I'm also in favor of using children, but here I don't see the point 🤔 

After it's quite the same, just wondering why it's "more idiomatic" ^^

**Comment by peterszerzo** [comment]
I find using `children` for this misleading - it hints at allowing the user to put anything and any number of items in there, which will largely stay unmodified. In this component, the input is both very specific and very heavily modified by the component. There is also a room for additional clarity by naming the prop descriptively, like `react-json-view` does it with `src`. I think we used `code` at some point, but `src` is better I'd say.
