### ISSUE TITLE
Add flexibility to casing of `CardItem` titles

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#726]
Currently, `CardItem` uppercases all characters in whatever string is passed to its `title` prop. This removes some more fine-grained control from users of this component. What if I want title case? What if I want lowercase? 

Ideally, this component would be able to be extended.

I am in favor of removing the case functionality whatsoever and leaving that up to the user.

Comments @fabien0102?

**Comment by TejasQ** [comment]
Yes.

I am unable to implement this design, as specified by our design team using `CardItem`, because `Your organization` becomes `YOUR ORGANIZATION`.

![image](https://user-images.githubusercontent.com/9947422/45295820-4fe78300-b500-11e8-88e4-08136d088202.png)

I would prefer this guarantee to be the responsibility of the developer, instead of the library forcing me into a certain type of casing.

**Comment by peterszerzo** [comment]
Did the design team specify that the `CardItem` component should be used to implement that piece of UI?

**Comment by TejasQ** [comment]
No, but it looks like a card item, doesn't it? What else would I use here? What do we want users of our libraries to use here?

**Comment by peterszerzo** [comment]
(oh, gosh, sorry for replying so late)

Looking at it again, it looks like the element is identical to form labels, not so much `CardItem` headings. So if we use them as `CardItem`'s and then someone later changes the form label, this will grow inconsistent. Wouldn't it be better if we made the internal form label component public and you used that for this case?

**Comment by TejasQ** [comment]
Yes! Let's do that!
