### ISSUE TITLE
Improve `ContextMenu` typings

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#737]
Currently, `ContextMenu` takes either a list of strings or a list of object (label + onClick fields) to specify its items. In its global click handler, the value passed may be either of those two types, and the compiler is currently unable to infer that if strings are passed in, strings should be passed to the handler, requiring an extra type-casting. This issue is a discussion point on how to handle this.

We can either improve typings with discriminating unions, or drop the possibility for specifying multiple data types, adjusting the input structure so it caters to all use-cases in a single interface.

Opinion ahead: I am leaning towards the second option, which carries the extra benefit of preventing codebases that deal with context menus in a way that is inconsistent to read.

**Comment by TejasQ** [comment]
Closed in #751 and #autocom
