### ISSUE TITLE
[Suggestion] Remove Lodash

### ISSUE THREAD

**Issue by adeelibr** [contiamo/operational-ui#752]
First of all, the work that you guys are doing is amazing. Very well maintained. Being a library maintainer. One of the major things that is of concern is the library size, specially when it is for a frontend related.

Currently there are 3 places in your entire library, which is using Lodash

1- Checkbox
https://github.com/contiamo/operational-ui/blob/67ab23ed89f16e8e92286d0bfeba5cb7b713ed2a/src/Checkbox/Checkbox.tsx#L1
https://github.com/contiamo/operational-ui/blob/67ab23ed89f16e8e92286d0bfeba5cb7b713ed2a/src/Checkbox/Checkbox.tsx#L98

We can generate a unique id, e.g, timestamp. 

I think the id, prop behavior shouldn't be hard coded like this. The use should be exposed to this prop. As to he/she can add the `id`.

2- Code
https://github.com/contiamo/operational-ui/blob/67ab23ed89f16e8e92286d0bfeba5cb7b713ed2a/src/Code/Code.tsx#L1
https://github.com/contiamo/operational-ui/blob/67ab23ed89f16e8e92286d0bfeba5cb7b713ed2a/src/Code/Code.tsx#L175

We can use `Array.filter` instead of omit.

3- OperationalUI

https://github.com/contiamo/operational-ui/blob/67ab23ed89f16e8e92286d0bfeba5cb7b713ed2a/src/OperationalUI/OperationalUI.tsx#L3
https://github.com/contiamo/operational-ui/blob/67ab23ed89f16e8e92286d0bfeba5cb7b713ed2a/src/OperationalUI/OperationalUI.tsx#L154

Wouldn't this include the entire library `import { Cancelable } from "lodash" `?

Again just 2 cents on my opinion. Going through your code base was fun. Typescript is new to me 😅 Did an hour crash course with `.ts` before coming to this repo.

**Comment by adeelibr** [comment]
Also I checked, since you are using `parcel` for bundling. Which I think is awesome. Parcel brings more to the table.  There is a `dev-dependency` for `webpack` which I guess is not needed any more. So it should be removed.

**Comment by peterszerzo** [comment]
`webpack` is used by styleguidist I believe, so it'd be best if it stuck around. The reason we have both that and parcel is that parcel is better for quick prototyping that doesn't make the rather large documentation page reload.

Can you outline how `Array.filter` replaces `lodash/omit`? Keep in mind that `omit` removes fields from an object, and not members from an array.

**Comment by adeelibr** [comment]
Sorry I didn't mean `Array.filter`, we can use a collection of `Object.entries, filter & reduce` to remove the usage of `_.omit`

```
  Object.entries(obj)
     .filter(([key]) => !['blacklisted', 'keys'].includes(key))
     .reduce((obj, [key, val]) => Object.assign(obj, { [key]: val }), {});
```

**Comment by peterszerzo** [comment]
That's a lot to read through - looks like something we'll wind up extracting into a utils method, and at that point we might as well just use `lodash`.

**Comment by adeelibr** [comment]
Yes you are right, but one of the largest challenges of a library is to have reduced bundled size, where every /kb matters. If you look at the `lodash` implementation of `omit, uniqueId, Cancelable` they have implemented in such a way where it handles loads of use cases. Some use cases that are redundant for our case.

In `Lodash` implementation of `omit`, there is a small comment above the implemented function which says 

> **Note:** This method is considerably slower than `_.pick`.

[Reference of comment from lodash repository](https://github.com/lodash/lodash/blob/67389a8c78975d97505fa15aa79bec6397749807/lodash.js#L13479)

Source code of `omit` implementation, which I think is very bloated.

https://github.com/lodash/lodash/blob/67389a8c78975d97505fa15aa79bec6397749807/lodash.js#L13495

But again, this was just an opinion of mine. If you think that lodash is an important part of Operational-UI i can understand. I was sharing my 2 cents. 😄

**Comment by peterszerzo** [comment]
Excellent point. So as not to get so hopelessly lost in details, let me answer the entire issue:
- `Cancelable` was imported from the whole library because of a typescript compiler issue that has since been resolved. I think we can do it properly this time. I would refrain from 
- the `omit` can be removed by either adding the props manually or doing a `const { src, collapsed, shouldCollapse, ...containerProps } = props` statement. I think it's more expressive this way, because `omit`-style code makes it looks like we're dealing with a fully dynamic dictionary and not a well-define object.

**Comment by adeelibr** [comment]
@peterszerzo can I make a PR to replace `lodash` **omit** with the spread syntax?

**Comment by TejasQ** [comment]
Yes, @adeelibr. PRs are _always_ welcome!
