### ISSUE TITLE
[Feature] Docs - Add Contributing.md file

### ISSUE THREAD

**Issue by adeelibr** [contiamo/operational-ui#756]
The repository should have Contributing.md file which outlines the way how any one can come and start contributing to 'Operational-UI` library. This is specially helpful for new contributors, setting up a guideline that outlines from creating a fork, pointing the master origin (upstream) to the original repository, creating a pull request etc.

I am more then happy to create a PR for this.

**Comment by adeelibr** [comment]
@TejasQ can I add an initial template for the contributing guide? :)

**Comment by adeelibr** [comment]
Update I am preparing the content for it, hopefully have a PR by today.

**Comment by TejasQ** [comment]
Added in #763
