### ISSUE TITLE
Need carets 🥕

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#760]
We have new icon requirements based on internal designs for carets:

![image](https://user-images.githubusercontent.com/9947422/46090322-7c490380-c17e-11e8-8681-36c81e977685.png)

cc @peterszerzo

**Comment by peterszerzo** [comment]
I'll have some carets going this evening - if there are needs until then, please use chevrons.

**Comment by TejasQ** [comment]
@peterszerzo any news here?

**Comment by peterszerzo** [comment]
Drawing them right now!
