### ISSUE TITLE
Give a proper API to `Table.__experimentalRowActions`

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#766]
In order to produce this kind of table:
![image](https://user-images.githubusercontent.com/1761469/46338542-bb6cce00-c630-11e8-901d-6c1cde98cacb.png)

we need to use `__experimentalRowActions`, since it's a quite commun case, I think it's time to give a proper API to this feature.

**Comment by peterszerzo** [comment]
I think the reason we kept it this way is that we weren't all on board with the API and we needed a quick solution. So the simplest solution would be to just rename to `rowActions` and adjust the UI as you wish with the same API - or change it slightly to suit our needs.

**Comment by adeelibr** [comment]
Can I work on this? :) @peterszerzo

**Comment by TejasQ** [comment]
@adeelibr, sorry, Peter has already been working on this!
