### ISSUE TITLE
Improve `HeaderMenu` and `ContextMenu` types

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#778]
### Problem

```tsx
<HeaderMenu
  items={[
    { label: "My Organization", value: "organization" },
    ...me.realms.map(realm => ({ label: realm.name, value: realm })),
  ]}
  onClick={selected => {
    /* selected is string | IContextMenu<any> | undefined */
  }}
  withCaret
>
  /* I can't put a string here => Type 'string' is not assignable to type 'ReactNode[]' */
</HeaderMenu>
```

Ideally, `selected` should be `IContextMenu<Realm | string>` and I should be able to put a simple `string` into `children` (the current workaround is to do `{["my string"]}` as `children`…)

**Comment by TejasQ** [comment]
Can I please work on this?

**Comment by TejasQ** [comment]
I don't understand the use case of `children` for this component though. The `value` is set in a prop and it really shows nothing inside it...
