### ISSUE TITLE
z-index issues :(

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#785]
So we have a bit of a z-index conflict going on: 
![image](https://user-images.githubusercontent.com/9947422/46798318-e0102680-cd51-11e8-9b5c-10b0d69fbc3c.png)

In order to fix it, either:

- `ContextMenu` or `HeaderMenu` needs a higher z-index, or
- `Progress` needs a lower one.

I think the first option makes the most sense because progress always needs to be visible and thus lowering its z-index might mask it in some cases.

Thoughts? @peterszerzo @ImogenF

**Comment by peterszerzo** [comment]
@TejasQ the progress bar shouldn't be there in the first place from a design perspective - we should either replace it with a spinner for pages or find a way to put the progress bar all the way up like on github's interface. Portals may help, though they'll complicated setup, unless the `OperationalUI` renders the portal content straight off the bat. I realize this is murky territory, but maybe we can come up with something :)

**Comment by TejasQ** [comment]
Waaaaait so the progress bar is only supposed to be on the very top?

**Comment by peterszerzo** [comment]
You're right :)

**Comment by TejasQ** [comment]
Awesome! I'll add that to #788!
