### ISSUE TITLE
HeaderMenu needs an icon next to its label

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#787]
To follow our design conventions, the word "Frontends" here needs to have its respective icon before it instead of being just plain text there.

![image](https://user-images.githubusercontent.com/9947422/46798884-7b55cb80-cd53-11e8-8f63-11f10168ed13.png)

**Comment by fabien0102** [comment]
![image](https://user-images.githubusercontent.com/1761469/47166271-0d357980-d2fc-11e8-8462-c0f832b216f6.png)
 I saw this in production, so I guess that is fixed 🤔 

@TejasQ can you confirm?

**Comment by TejasQ** [comment]
It is. The solution is to just put `<Icon name="Project" left /> Frontends` in its children.
