### ISSUE TITLE
Create a `Foldable` component

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#809]
### Summary
![image](https://user-images.githubusercontent.com/1761469/47575415-557b1a00-d942-11e8-94d4-c745c6f3e122.png)

The idea is to have a nice foldable component

### API Proposal

```tsx
<Foldable title="Jobs"><Code /></Foldable>

**Comment by TejasQ** [comment]
@micha-f maybe this would help even our card sections and resource-role-assigner.

What if we had a 

```jsx
<Foldable>
  {({ Toggler }) => {
    return <Card title={<>Hello <Toggler />}>My Card</Card>
  }}
</Foldable>
```

that would make a card foldable? This could be applied to any component that we would like to be foldable. 😄

**Comment by TejasQ** [comment]
This was merged.
