### ISSUE TITLE
Cannot copy JSON from Code component

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#812]
Problems when copying:
* `# items` are copied
* No `,` to separate properties

![image](https://user-images.githubusercontent.com/200647/47653686-679ac980-db89-11e8-902a-95bd9428a209.png)

**Comment by fabien0102** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a copy button to Code json](https://trello.com/c/eXcDJArA/547-add-a-copy-button-to-code-json)
