### ISSUE TITLE
Card columns / sections that are not of equal width

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#815]
How can we best support CardColumns / Sections that are not of equal width?

**Comment by fabien0102** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Card columns / sections that are not of equal width](https://trello.com/c/IpYses34/613-card-columns-sections-that-are-not-of-equal-width)

**Comment by TejasQ** [comment]
Odd. I can't seem to remember what this issue was about. Can we either:

- provide more context, or
- close it

?
