### ISSUE TITLE
Page without title are not well dimensionned

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#834]
### Problem
If the page don't have any `title` props, the height is not well calculed and we have this weird scroll cut off on the end the page

![image](https://user-images.githubusercontent.com/1761469/48625519-c9439c00-e9af-11e8-9a02-47ee606b0078.png)

### Codesandbox
[![Edit k9wwrlrq5v](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k9wwrlrq5v)

**Comment by fabien0102** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Page without title are not well dimensionned](https://trello.com/c/t8QtIpPI/611-page-without-title-are-not-well-dimensionned)

**Comment by TejasQ** [comment]
AFAIK we had a guarantee that Pages would _always_ have titles. If we change requirements, we need to communicate them. 🙂 Will fix. cc @micha-f

**Comment by TejasQ** [comment]
Closing because #839 was merged.
