### ISSUE TITLE
Improve Hint API and style

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#837]
![image](https://user-images.githubusercontent.com/1761469/48775316-fc966b80-eccc-11e8-842f-e91560440e30.png)

### Problems

- The `bundles` is cut without obvious reasons
- I can't choose the position of the tooltip
- The text is not correctly centered

### Proposed API

```tsx
interface HintProps {
  tooltipPosition: "top" | "right" | "bottom" | "left"
  iconPosition: "right" | "left"
  tooltip: React.ReactNode
  children: React.ReactNode
}
```

### Usage
**Without i18n**
```tsx
<Hint 
  tooltip="A useful message to help my user"}
  tooltipPosition="bottom"
>
  A text that need explaination
</Hint>
```
**With i18n**
```tsx
<Hint 
  tooltip={<FormattedMessage id="my.tooltip.message" />}
>
  <FormattedMessage id="my.content" />
</Hint>
```

### Bonus points

Ideally I don't want to set the `tooltipPosition`, the `Tooltip` should be able to choose itself the best position regarding the space available in the UI.

**Comment by peterszerzo** [comment]
@fabien0102 what do you mean by `text is not centered correctly`?

**Comment by fabien0102** [comment]
Good question, to be honest, I don't remember 😄 Maybe when the hint is set with another position 🤔

**Comment by TejasQ** [comment]
Let's reopen this at a later stage since hints are working pretty well for us so far.
