### ISSUE TITLE
Deprecate `Foldable`

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#869]
Currently, the `Foldable` component manages folded state internally and exports a full-width overlay for toggling, all through render props. The PR https://github.com/contiamo/operational-ui/pull/863 also adds a controlled version of it where state can be managed on the outside. We are getting to a point where control is inverted into render props with little benefits, confusing intent and opening up the door for UI bugs such as the overlay covering other controls.

For the controlled case, I think it would be clearer to just expose the `Toggler` component directly (and without full-width to have it play nicely with other controls) and have components use it with their own state management. Render props give the impression that state is managed internally, only to find out that it is actually controlled on the outside. I find that very confusing to read.

Since more and more use-cases are popping up when folded state is managed from the outside, I'm wondering whether this component is worth having around at all. Managing one folded state case-by-case is not that much extra work, and adds a lot of clarity and control.

**Comment by TejasQ** [comment]
This isn't really causing us any issues right now so let's close this and reopen it at a later date if/when we need to.
