### ISSUE TITLE
Icons renaming / aliases

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#884]
### Root cause

We don't have `Olap` and `Entity` names anymore in our applications (this was renamed to `Aggregate` and `Record`)

### Proposition

I don't really like the hard link between icon name and our product concept names (bundle, olap, entity…), it's maybe time to consider to introduce some icons alias and give more generic names.

**Comment by peterszerzo** [comment]
What is important to consider when taking the step you're proposing @fabien0102 is that if we give these icons generic names, we're making it easier for anyone to sprinkle them all over the UI for unrelated reasons and make things confusing. If we want the cube icon for instance to be a unique icon for an aggregate query and not risk being used someplace else as e.g. a bundle, we should keep calling them `Aggregate`.

**Comment by TejasQ** [comment]
Icons are now named whatever marketing wants – they decide by naming their SVG files.
