### ISSUE TITLE
Support tabs in card column titles

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-ui#891]
![image](https://user-images.githubusercontent.com/200647/50832035-3854c580-134d-11e9-889d-44506c81e551.png)

They should work the same way as card header tabs.

**Comment by micha-f** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support tabs in card column headers](https://trello.com/c/zKQTSUCg/671-support-tabs-in-card-column-headers)

**Comment by TejasQ** [comment]
We have this now.
