### ISSUE TITLE
Open the DatePicker on the correct page if `max` is set

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#909]
## Summary

Actually the `DatePicker` component always open on the current date, even if we have the `max` props set.

It's very annoying so let's fix this! 😄

**Comment by rimildeyjsr** [comment]
@fabien0102 - Hey I am interested in taking this up! 

Would this be a good first bug to start with? All the other first bugs are currently taken up 😅

**Comment by fabien0102** [comment]
@rimildeyjsr Hey! Welcome to the project 🎉 

Definitely a good first issue! Don't hesitate if you have any questions 😃

**Comment by TejasQ** [comment]
Hey @rimildeyjsr! Have you been able to find time for this issue yet? What can we help/support you with?

**Comment by rimildeyjsr** [comment]
@TejasQ - hey had a very busy work week, so didn't have a chance to work on it. Will definitely take this up in the weekend. Sorry for the delay.

I will start by looking at the datepicker component's source code, if I have any doubts, I will definitely reach out!

**Comment by TejasQ** [comment]
Awesome! Looking forward to your PR!

**Comment by rimildeyjsr** [comment]
@TejasQ @fabien0102 - Hey, I went over the source code for the Datepicker component and found the area of code to be changed. It is this piece of code in the `DatePicker.tsx`

```
const startYearMonthInWidget = props.start
      ? 
      {
          year: toYearMonthDay(props.start).year,
          month: toYearMonthDay(props.start).month,
        }
      :
      {
          year: new Date().getFullYear(),
          month: new Date().getMonth(),
        }
```

If I add in another if statement to also check for `props.max` and add in the appropriate year and month, the date picker opens on to the proper page.

I had one question to ask - Should we also not handle other cases? Like if both `start` and `max` props are not available, but the `min` or `end` props is, shouldn't the page open on the month having the min or end date, rather than the current date.

I just wanted to ask how to handle all edge cases, since the more I think about it, the more edge cases come to mind!

**Comment by TejasQ** [comment]
Great questions, @rimildeyjsr! Maybe we can have a function with a lot of conditionals that handle edge cases and throw/warn where appropriate? Something like `validate()` or similar? I think that could be a good first direction.

**Comment by rimildeyjsr** [comment]
@TejasQ @fabien0102 - Hey this is the solution I am proposing. Let me know if I can clean up the code more, add/delete something or if there is any better way of doing this! 

If the solution looks good, I will create the PR!

So in the `DatePicker.tsx` file, I am assigning `startYearMonthInWidget` to the return value of `this.getStartMonthYearInWidget(props)`. The function is checking if the start, end, max, or min props are available incrementally, and if they exist returns that value as the starting month and year. I referenced the `validate()` function while writing the function for the type of `props` and for `validatedProps`.

```
public getStartMonthYearInWidget(props?: DatePickerProps) {
    // set start month and year of the widget based on the availability of start, end, max, or min props.
    // if none of the props are available, set it to the current month and year.
    const validatedProps = props || this.props;
    return (
      validatedProps.start ?
        {
          year: toYearMonthDay(validatedProps.start).year,
          month: toYearMonthDay(validatedProps.start).month,
        }
      :
      validatedProps.end ?
        {
          year: toYearMonthDay(validatedProps.end).year,
          month: toYearMonthDay(validatedProps.end).month,
        }
      :
      validatedProps.min ?
        {
          year: toYearMonthDay(validatedProps.min).year,
          month: toYearMonthDay(validatedProps.min).month,
        }
      :
      validatedProps.max ?
        {
          year: toYearMonthDay(validatedProps.max).year,
          month: toYearMonthDay(validatedProps.max).month,
        }
      :
        {
          year: new Date().getFullYear(),
          month: new Date().getMonth(),
        }
    );
  }
```

**Comment by TejasQ** [comment]
@rimildeyjsr this idea looks a little abstract for me to piece together all the context, but let's try it! Open your PR!

**Comment by rimildeyjsr** [comment]
@TejasQ - Opened a PR! 😃
