### ISSUE TITLE
[Umbrella] Tree component features

### ISSUE THREAD

**Issue by stereobooster** [contiamo/operational-ui#923]
List of features we may want to add to `Tree` component which were discussed in @TejasQ PR https://github.com/contiamo/operational-ui/pull/919

- [ ] controlled version of tree component
- ~~`meta` field - to be able to attach additional data to node, to use it later in `onNodeClick` handler~~
- ~~`node` render prop - to override how leaf rendered~~
- [ ] support reorder for non-leaf nodes

**Comment by fabien0102** [comment]
We took another direction for this component ;)
