### ISSUE TITLE
<Tour />

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#965]
## Motivation
We want to have a really comfortable way to guide users through our system as they begin using it: AKA onboarding.

## Appearance
[Internal Contiamo Link](https://app.zeplin.io/project/5b22288192fd37d946cb6acb/screen/5c8a8dfb83d1b52501ba81a8)

## Behavior

    ┌──────────────────────────────────────┐     ┌──────────────────────────────────────┐     ┌──────────────────────────────────────┐
    │░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│     │○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○│     │░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
    │░░░░░┌──────────────────────────┐░░░░░│     │○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○│     │░░░░┌─────────────────────────────┐░░░│
    │░░░░░│      ┌────────┐          │░░░░░│     │○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○│     │░░░░│        ┌──────────┐         │░░░│
    │░░░░░│      │Welcome │          │░░░░░│     │○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○│     │░░░░│        │Conclusion│         │░░░│
    │░░░░░│      └────────┘          │░░░░░│     │○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○│     │░░░░│        └──────────┘         │░░░│
    │░░░░░│      ┌─┐┌─┐┌─┐┌─┐        │░░░░░│     │○○○○○○○○○○○○○○○○○○┌─────────────────┐○│     │░░░░│        ┌─┐┌─┐┌─┐┌─┐         │░░░│
    │░░░░░│      └─┘└─┘└─┘└─┘        │░░░░░│     │○○○○○○○○○○○○○○○○○○│ ┌───────────┐   │○│     │░░░░│        └─┘└─┘└─┘└─┘         │░░░│
    │░░░░░│                          │░░░░░│ ==> │○○○○○○○○○○○○○○○○○○│ │About X... │   │○│ ==> │░░░░│                             │░░░│
    │░░░░░│                          │░░░░░│     │○○○○○○○○○○○○○○○○○○│ └───────────┘   │○│     │░░░░│                             │░░░│
    │░░░░░│          ┌──────┐┌─────┐ │░░░░░│     │○○○○○○○○○○○○○○○○○○│ ┌─┐┌─┐┌─┐┌─┐    │○│     │░░░░│          ┌───────┐          │░░░│
    │░░░░░│          │Cancel││Start│ │░░░░░│     │○○○○○○○○○○○○○○○○○○│ └─┘└─┘└─┘└─┘    │○│     │░░░░│          │Finish │          │░░░│
    │░░░░░│          └──────┘└─────┘ │░░░░░│     │○○○○○○○○○○○○○○○○○○│  ┌──────┐┌─────┐│○│     │░░░░│          └───────┘          │░░░│
    │░░░░░└──────────────────────────┘░░░░░│     │○○○○○○○○○○○○○○○○○○│  │Cancel││Next ││○│     │░░░░└─────────────────────────────┘░░░│
    │░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│     │○○○○○○○○○○○○○○○○○○└──┴──────┴┴─────┴┘○│     │░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
    └──────────────────────────────────────┘     └──────────────────────────────────────┘     └──────────────────────────────────────┘

The behavior of the guided tour is described as so:

- INITIAL STATE
    - displays a nice welcome message (modal)
        - it should have a way for the user to cancel it
            - it should go to the END STATE on cancel
        - it should have a breadcrumb to provide a user with context
            - the breadcrumb is interactive and allows jumping through sections
        - it should allow the user to proceed (next →)
- RUNNING STATE
    - displays (static!) screens that illustrate the concepts it describes
        - when displaying illustrative screens, the modal should be off-center of the screen, in the lower-right corner, in order to highlight the illustration
        - the illustrations are actual pages/components with mock data
        - the modal
            - is smaller, maximizing the display area of the illustrations
            - it continues to provide the user with context
            - it continues to allow the user to proceed
            - it continues to allow the user to cancel it and go to the END STATE
- END STATE
    - Should display a modal exactly like the first screen with "This concludes the tour [...]"
    - Should go to a defined route on click of "finish"
    - Should **not** have a cancel button

### Visual Representation

The flow of this tour, should look similar to:

    	┌────────────────────┐                            
            │                    │                            
            ▼                    │                            
    ┌──────────────┐     ┌──────────────┐     ┌──────────────┐
    │              │     │              │     │              │
    │  ┌───────┐   │     │  ┌───────┐   │     │   ┌───────┐  │
    │  │ Start │   │────▶│  │ Steps │   │────▶│   │Finish │  │
    │  └───────┘   │     │  └───────┘   │     │   └───────┘  │
    │              │     │              │     │              │
    └──────────────┘     └──────────────┘     └──────────────┘
            │                    │                    ▲       
            └───────────┬────────┘                    │       
                        │                             │       
                        ▼                             │       
                        Λ                             │       
                       ╱ ╲                            │       
                      ╱   ╲                           │       
                     ╱     ╲                          │       
                    ╱       ╲                         │       
                   ╱┌──────┐ ╲                        │       
                  ▕ │Cancel│  ▏───────────────────────┘       
                   ╲└──────┘ ╱                                
                    ╲       ╱                                 
                     ╲     ╱                                  
                      ╲   ╱                                   
                       ╲ ╱                                    
                        V

## API/Usage

Let's have a `Tour` that is created like so:

```tsx
interface TourItem {
    id: string
    body: React.ReactNode
    /* Icon registers the item in the navigation */
    icon?: React.ReactNode
    /* When illustration is present, the modal is no longer center-stage */
    illustration?: React.ReactNode
}
```
    

This component can be controlled by a parent's state like so

```ts
import * as React from "react"
import { Tour } from "@operational/components"

const MyComponent = () => {
    const [currentPage, setCurrentPage] = React.useState("start")

    return <Tour 
            currentPage={currentPage}
            onPageChange={newPage => setCurrentPage(newPage.id)}
            onFinish={() => alert("Great!")}
            pages={
                [
                    { 
                        id: "start",
                        body: <><h1>Welcome to Step 1!</h1><p>Welcome to my tour!</p></>,
                    },
                    { 
                        id: "data-sources",
                        icon: <Icon name="Cube" />,
                        body: <><h1>Data Sources</h1><p>Data Sources are nice because X</p></>,
                        illustration: <Table name="Data Sources" data={data} />,
                    },
                ]
            }
        />
}

; <MyComponent />
```

Alternatively, we would add a route to Contiamo UI to control its state via the router:

```tsx
<Route
    path="/tour/:tourId"
    render={routerProps => () => {
        return <Tour 
            currentPage={routerProps.match.params.tourId}
            onPageChange={newPage => routerProps.history.push(newPage.id)}
            onFinish={() => routerProps.history.push('/data-sources/new')}
            pages={
                [
                    { 
                        id: "start",
                        body: <><h1>Welcome to Step 1!</h1><p>Welcome to my tour!</p></>,
                    },
                    { 
                        id: "data-sources",
                        icon: <Icon name="Cube" />,
                        body: <><h1>Data Sources</h1><p>Data Sources are nice because X</p></>,
                        illustration: <Table name="Data Sources" data={data} />,
                    },
                ]
            }
        />
    }}
/>
```

Thoughts? Questions? Concerns?

One additional concern I have (maybe for the next iteration) is to highlight given DOM elements _under_ the overlay. If you have ideas, I'd appreciate it.

**Comment by micha-f** [comment]
Should this be in Operational UI? It seems like a very specific component / functionality. Shouldn't it live inside of Contiamo UI for now? At least until we see how well it does and what changes we might have to make in the next months based on feedback?

**Comment by stereobooster** [comment]
How would you provide fake state for the pages? Based on route?

**Comment by TejasQ** [comment]
@micha-f 

> Should this be in Operational UI? It seems like a very specific component / functionality. Shouldn't it live inside of Contiamo UI for now? At least until we see how well it does and what changes we might have to make in the next months based on feedback?

I don't see why it _shouldn't_ live in Operational UI. 🤔  It's a UI component that we might reuse at different levels within the product? Unless there are strong objections to including it here, I don't really understand why we'd couple it to some internal component.

@stereobooster 

> How would you provide fake state for the pages? Based on route?

What do you mean by pages? Do you mean steps/pages _in the tour_? Or do you mean illustrations/"demo page" that the tour shows?

**Comment by micha-f** [comment]
@TejasQ It seems too opinionated to me to be in Operational. First screen in the middle, all until finish in the bottom right, icons to keep track of current step. It's our "welcome tour" - I don't see us using this in many other places ;).

**Comment by TejasQ** [comment]
You're right. We discussed it and decided to keep it simple:

We'll add a simple modal based on `Internals/Modal` to Operational that aligns itself to "tour areas" per the design and call it a `TourModal`. We'll use this to implement the screens.
