### ISSUE TITLE
Make Table actions accessible

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#971]
> ⚠️ This was originally posted by @mpotomin in an internal Contiamo channel.

## Motivation

Currently it is not possible to navigate the Table from the keyboard. Also, nothing gives the idea, that there are row actions attached to each item in the Table (gif attached). When triggered, the row actions menu disappears when mouse roll out from the window and there is no way to keep it on the screen (since there is no :focus handling).

![FE-44_Table_actions_improvement-f22b18d3-ed76-4cc1-8b8f-86b66c37b8a8](https://user-images.githubusercontent.com/9947422/55091243-c1f47380-50b0-11e9-9c09-abad15d8d8c7.gif)

## Suggestion:

1. Tab-cycling through the page should include the table to allow triggering the row actions from the keyboard.
2. Since we hide the context menu (should we, though?) every time the mouse pointer rolls out from the page, the style of the row should be modified so that the action menu stays on the screen and can be navigated if the Table row has the focus (focus would force the behaviour, that the table row currently shows on :hover)

https://github.com/contiamo/operational-ui/blob/39461d66c2bb861afd563b78431faa01877c7baa/src/Table/Table.tsx#L124

Possibly needs smth like & :focus here

**Comment by TejasQ** [comment]
@mpotomin this is a great idea. Take caution though that `<div />` elements have no support for `:focus` states. I would recommend turning them (from `ActionMenu`) into `<button />`s and then adding the `:focus` handling.

**Comment by MaximKazionov** [comment]
Can I take it?

**Comment by TejasQ** [comment]
Yes you can!

**Comment by TejasQ** [comment]
@MaximKazionov what's your plan?

**Comment by kazionovm** [comment]
@TejasQ take a look at this article
[solved-with-css-dropdown-menus](https://css-tricks.com/solved-with-css-dropdown-menus/)

**Comment by TejasQ** [comment]
@kazionovm that looks cool. Was that your plan? I kind of already solved it 😬 because I was bored on a plane. Would love your review on the PR.
