### ISSUE TITLE
Button Remounted on every render

### ISSUE THREAD

**Issue by JoshRosenstein** [contiamo/operational-ui#984]
**Problem:** Button currently creates the Container within itself which is not optimal as it creates a new component on every render.
https://github.com/contiamo/operational-ui/blob/402249ae501e468c5b3ad8ccd5fc581a70836b22/src/Button/Button.tsx#L86
**Suggestion:** extract container out, utilized emotions `as` prop to render a anchor if `to` prop is passed. 

**Origin:** #468 

**Example:**
current button vs button with suggested changes can be viewed here:
[![Edit Operational-ui Button Issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8lqrj509oj?expanddevtools=1&fontsize=14)
(updated the example to also show how the Test in the comments below works)

PR on standby.

------
### Edit
 Extracting out Container also initializes a step for completing #944 

Searched for some components with this similar issue and found:
https://github.com/contiamo/operational-ui/blob/d72016c11638a4dd751b2b0396c13470951644a7/src/SidenavItem/SidenavItem.tsx#L120
https://github.com/contiamo/operational-ui/blob/f59c010633c3503c77787838fa6271756e4f3ace/src/Breadcrumb/Breadcrumb.tsx#L39
(memo does not work here)
https://github.com/contiamo/operational-ui/blob/c84c10aaa754649587a7c41aade0e155d9e2f06d/src/SimpleLink/SimpleLink.tsx#L31-L32
https://github.com/contiamo/operational-ui/blob/ecc692971b6f207c9d78080addb98d4b4ee7f522/src/SidenavHeader/SidenavHeader.tsx#L136

**Comment by JoshRosenstein** [comment]
I Also wanted to write some sort of test for this. Below is a test for the test 😆 . Comparing the fixed button solution to the current button.

Below currently ✅ , so i will extract out this testing method and put it under some __testUtils__ folder that way it can be applied to this future PR, but also for any of the other components that have this issue.
```ts
import * as React from "react"
import { mount } from "enzyme"
import { Button as ThemelessButton } from "../../index"
import ThemelessButton2  from "../ButtonOld"
import wrapDefaultTheme from "../../utils/wrap-default-theme"

// The 'fixed' Button 
const Button = wrapDefaultTheme(ThemelessButton)
// The Old Button --- This is only here to make sure this test captures the underlying issue
const Button2 = wrapDefaultTheme(ThemelessButton2)

/// Functions used to identify number times a component re-mounts
const Button1ChildMountFN= jest.fn()
const Button2ChildMountFN= jest.fn()

/// Will Call mock function if parent aka Button mounts
class Child extends React.Component<any> {
  componentWillMount() {
    Button1ChildMountFN(this.props.id)
  }
  render() {
    return  <div >{this.props.id}</div>
  }
}

/// Child for old button 
class Child2 extends React.Component<any> {
  componentWillMount() {
    Button2ChildMountFN()
  } 
  render() {
    return  <div />
  }
}

const ButtonTest = ({ onClick, count }:any) => {
  return (
    <React.Fragment>
      <button id="update Counter" onClick={onClick}>Count: {count}</button>
      <Button> <Child/> </Button>
      <Button2> <Child2/> </Button2>
    </React.Fragment>
  );
};

// tslint:disable-next-line: max-classes-per-file
class TestWrapper extends React.Component<{},{count:number}> {
  constructor(props:any) {
    super(props)
    this.state = { count: 1 };
  }
  // This isnt needed for test file, but left it there for browser inspecting 
  handleClick = () => {
    this.setState(state => ({ count: state.count + 1 }));
  };

  render() {
    return <ButtonTest onClick={this.handleClick} count={this.state.count} />
  }
}

describe("Fixed Button vs Old Button", () => {
  
it("Remounts as expected", () => {
const m = mount(<TestWrapper/>)
/// Lets Update the state 4 Times
m.setState({count:1})
m.setState({count:2})
m.setState({count:3})
m.setState({count:4})

/// Fixed Button Child should have only mounted once
expect(Button1ChildMountFN).toBeCalledTimes(1)

/// Old button mounts 1 + number of state change = 5
expect(Button2ChildMountFN).toBeCalledTimes(5)
})


})

```

**Comment by JoshRosenstein** [comment]
So now that the test method above correctly tests this issue, we can create a test Helper and test it like:
```ts
import { Button as ThemelessButton } from "../../index"
import ThemelessButton2  from "../ButtonOld"
import wrapDefaultTheme from "../../utils/wrap-default-theme"
import {itShouldOnlyMountOnce} from "../../__testUtils__/itShouldOnlyMountOnce"

// The 'fixed' Button 
const Button = wrapDefaultTheme(ThemelessButton)
// The Old Button
const Button2 = wrapDefaultTheme(ThemelessButton2)

describe("Fixed Button vs Old Button", () => {
  
  itShouldOnlyMountOnce("FixedButton",Button)

  itShouldOnlyMountOnce("OldButton",Button2) 
/**
 * FAIL-> Fixed Button vs Old Button › [OldButton] should only mount once
 * Expected mock function to have been called one time, but it was called five times.
 */

})

```

Will include itShouldOnlyMountOnce in the PR.

**Comment by TejasQ** [comment]
Dang. You've done a lot of good work here!

**Comment by TejasQ** [comment]
I'm not sure this is still an issue since we merged the PR. Closing.
